// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

/**
 * Protobuf type {@code google.spannerlib.v1.ConnectionStreamResponse}
 */
@com.google.protobuf.Generated
public final class ConnectionStreamResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.spannerlib.v1.ConnectionStreamResponse)
    ConnectionStreamResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      ConnectionStreamResponse.class.getName());
  }
  // Use ConnectionStreamResponse.newBuilder() to construct.
  private ConnectionStreamResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ConnectionStreamResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.spannerlib.v1.ConnectionStreamResponse.class, com.google.cloud.spannerlib.v1.ConnectionStreamResponse.Builder.class);
  }

  private int bitField0_;
  private int responseCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EXECUTE_RESPONSE(2),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 2: return EXECUTE_RESPONSE;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private com.google.rpc.Status status_;
  /**
   * <code>.google.rpc.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.rpc.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.google.rpc.Status getStatus() {
    return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.google.rpc.Status status = 1;</code>
   */
  @java.lang.Override
  public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
  }

  public static final int EXECUTE_RESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
   * @return Whether the executeResponse field is set.
   */
  @java.lang.Override
  public boolean hasExecuteResponse() {
    return responseCase_ == 2;
  }
  /**
   * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
   * @return The executeResponse.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ExecuteResponse getExecuteResponse() {
    if (responseCase_ == 2) {
       return (com.google.cloud.spannerlib.v1.ExecuteResponse) response_;
    }
    return com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ExecuteResponseOrBuilder getExecuteResponseOrBuilder() {
    if (responseCase_ == 2) {
       return (com.google.cloud.spannerlib.v1.ExecuteResponse) response_;
    }
    return com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStatus());
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (com.google.cloud.spannerlib.v1.ExecuteResponse) response_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.cloud.spannerlib.v1.ExecuteResponse) response_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.spannerlib.v1.ConnectionStreamResponse)) {
      return super.equals(obj);
    }
    com.google.cloud.spannerlib.v1.ConnectionStreamResponse other = (com.google.cloud.spannerlib.v1.ConnectionStreamResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 2:
        if (!getExecuteResponse()
            .equals(other.getExecuteResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    switch (responseCase_) {
      case 2:
        hash = (37 * hash) + EXECUTE_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getExecuteResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.spannerlib.v1.ConnectionStreamResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.spannerlib.v1.ConnectionStreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.spannerlib.v1.ConnectionStreamResponse)
      com.google.cloud.spannerlib.v1.ConnectionStreamResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.spannerlib.v1.ConnectionStreamResponse.class, com.google.cloud.spannerlib.v1.ConnectionStreamResponse.Builder.class);
    }

    // Construct using com.google.cloud.spannerlib.v1.ConnectionStreamResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      if (executeResponseBuilder_ != null) {
        executeResponseBuilder_.clear();
      }
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamResponse_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionStreamResponse getDefaultInstanceForType() {
      return com.google.cloud.spannerlib.v1.ConnectionStreamResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionStreamResponse build() {
      com.google.cloud.spannerlib.v1.ConnectionStreamResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionStreamResponse buildPartial() {
      com.google.cloud.spannerlib.v1.ConnectionStreamResponse result = new com.google.cloud.spannerlib.v1.ConnectionStreamResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.cloud.spannerlib.v1.ConnectionStreamResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = statusBuilder_ == null
            ? status_
            : statusBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(com.google.cloud.spannerlib.v1.ConnectionStreamResponse result) {
      result.responseCase_ = responseCase_;
      result.response_ = this.response_;
      if (responseCase_ == 2 &&
          executeResponseBuilder_ != null) {
        result.response_ = executeResponseBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.spannerlib.v1.ConnectionStreamResponse) {
        return mergeFrom((com.google.cloud.spannerlib.v1.ConnectionStreamResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.spannerlib.v1.ConnectionStreamResponse other) {
      if (other == com.google.cloud.spannerlib.v1.ConnectionStreamResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      switch (other.getResponseCase()) {
        case EXECUTE_RESPONSE: {
          mergeExecuteResponse(other.getExecuteResponse());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetExecuteResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.rpc.Status status_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.google.rpc.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     * @return The status.
     */
    public com.google.rpc.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    public Builder setStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    public Builder setStatus(
        com.google.rpc.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    public Builder mergeStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          status_ != null &&
          status_ != com.google.rpc.Status.getDefaultInstance()) {
          getStatusBuilder().mergeFrom(value);
        } else {
          status_ = value;
        }
      } else {
        statusBuilder_.mergeFrom(value);
      }
      if (status_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    public com.google.rpc.Status.Builder getStatusBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.google.rpc.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.google.rpc.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> 
        internalGetStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.ExecuteResponse, com.google.cloud.spannerlib.v1.ExecuteResponse.Builder, com.google.cloud.spannerlib.v1.ExecuteResponseOrBuilder> executeResponseBuilder_;
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     * @return Whether the executeResponse field is set.
     */
    @java.lang.Override
    public boolean hasExecuteResponse() {
      return responseCase_ == 2;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     * @return The executeResponse.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ExecuteResponse getExecuteResponse() {
      if (executeResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          return (com.google.cloud.spannerlib.v1.ExecuteResponse) response_;
        }
        return com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return executeResponseBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    public Builder setExecuteResponse(com.google.cloud.spannerlib.v1.ExecuteResponse value) {
      if (executeResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        executeResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    public Builder setExecuteResponse(
        com.google.cloud.spannerlib.v1.ExecuteResponse.Builder builderForValue) {
      if (executeResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        executeResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    public Builder mergeExecuteResponse(com.google.cloud.spannerlib.v1.ExecuteResponse value) {
      if (executeResponseBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance()) {
          response_ = com.google.cloud.spannerlib.v1.ExecuteResponse.newBuilder((com.google.cloud.spannerlib.v1.ExecuteResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          executeResponseBuilder_.mergeFrom(value);
        } else {
          executeResponseBuilder_.setMessage(value);
        }
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    public Builder clearExecuteResponse() {
      if (executeResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        executeResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    public com.google.cloud.spannerlib.v1.ExecuteResponse.Builder getExecuteResponseBuilder() {
      return internalGetExecuteResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ExecuteResponseOrBuilder getExecuteResponseOrBuilder() {
      if ((responseCase_ == 2) && (executeResponseBuilder_ != null)) {
        return executeResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (com.google.cloud.spannerlib.v1.ExecuteResponse) response_;
        }
        return com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteResponse execute_response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.ExecuteResponse, com.google.cloud.spannerlib.v1.ExecuteResponse.Builder, com.google.cloud.spannerlib.v1.ExecuteResponseOrBuilder> 
        internalGetExecuteResponseFieldBuilder() {
      if (executeResponseBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = com.google.cloud.spannerlib.v1.ExecuteResponse.getDefaultInstance();
        }
        executeResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.ExecuteResponse, com.google.cloud.spannerlib.v1.ExecuteResponse.Builder, com.google.cloud.spannerlib.v1.ExecuteResponseOrBuilder>(
                (com.google.cloud.spannerlib.v1.ExecuteResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();
      return executeResponseBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.spannerlib.v1.ConnectionStreamResponse)
  }

  // @@protoc_insertion_point(class_scope:google.spannerlib.v1.ConnectionStreamResponse)
  private static final com.google.cloud.spannerlib.v1.ConnectionStreamResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.spannerlib.v1.ConnectionStreamResponse();
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConnectionStreamResponse>
      PARSER = new com.google.protobuf.AbstractParser<ConnectionStreamResponse>() {
    @java.lang.Override
    public ConnectionStreamResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConnectionStreamResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConnectionStreamResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ConnectionStreamResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

