// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

/**
 * <pre>
 * ConnectionStreamRequest is used by a client to send a request to the server using a
 * bi-directional gRPC stream. Such a stream is opened by calling the ConnectionStream RPC.
 * </pre>
 *
 * Protobuf type {@code google.spannerlib.v1.ConnectionStreamRequest}
 */
@com.google.protobuf.Generated
public final class ConnectionStreamRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.spannerlib.v1.ConnectionStreamRequest)
    ConnectionStreamRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      ConnectionStreamRequest.class.getName());
  }
  // Use ConnectionStreamRequest.newBuilder() to construct.
  private ConnectionStreamRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ConnectionStreamRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.spannerlib.v1.ConnectionStreamRequest.class, com.google.cloud.spannerlib.v1.ConnectionStreamRequest.Builder.class);
  }

  private int requestCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EXECUTE_REQUEST(1),
    EXECUTE_BATCH_REQUEST(2),
    BEGIN_TRANSACTION_REQUEST(3),
    COMMIT_REQUEST(4),
    ROLLBACK_REQUEST(5),
    WRITE_MUTATIONS_REQUEST(6),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return EXECUTE_REQUEST;
        case 2: return EXECUTE_BATCH_REQUEST;
        case 3: return BEGIN_TRANSACTION_REQUEST;
        case 4: return COMMIT_REQUEST;
        case 5: return ROLLBACK_REQUEST;
        case 6: return WRITE_MUTATIONS_REQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int EXECUTE_REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
   * @return Whether the executeRequest field is set.
   */
  @java.lang.Override
  public boolean hasExecuteRequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
   * @return The executeRequest.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ExecuteRequest getExecuteRequest() {
    if (requestCase_ == 1) {
       return (com.google.cloud.spannerlib.v1.ExecuteRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ExecuteRequestOrBuilder getExecuteRequestOrBuilder() {
    if (requestCase_ == 1) {
       return (com.google.cloud.spannerlib.v1.ExecuteRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance();
  }

  public static final int EXECUTE_BATCH_REQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
   * @return Whether the executeBatchRequest field is set.
   */
  @java.lang.Override
  public boolean hasExecuteBatchRequest() {
    return requestCase_ == 2;
  }
  /**
   * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
   * @return The executeBatchRequest.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ExecuteBatchRequest getExecuteBatchRequest() {
    if (requestCase_ == 2) {
       return (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ExecuteBatchRequestOrBuilder getExecuteBatchRequestOrBuilder() {
    if (requestCase_ == 2) {
       return (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance();
  }

  public static final int BEGIN_TRANSACTION_REQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
   * @return Whether the beginTransactionRequest field is set.
   */
  @java.lang.Override
  public boolean hasBeginTransactionRequest() {
    return requestCase_ == 3;
  }
  /**
   * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
   * @return The beginTransactionRequest.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.BeginTransactionRequest getBeginTransactionRequest() {
    if (requestCase_ == 3) {
       return (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.BeginTransactionRequestOrBuilder getBeginTransactionRequestOrBuilder() {
    if (requestCase_ == 3) {
       return (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance();
  }

  public static final int COMMIT_REQUEST_FIELD_NUMBER = 4;
  /**
   * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
   * @return Whether the commitRequest field is set.
   */
  @java.lang.Override
  public boolean hasCommitRequest() {
    return requestCase_ == 4;
  }
  /**
   * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
   * @return The commitRequest.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.Connection getCommitRequest() {
    if (requestCase_ == 4) {
       return (com.google.cloud.spannerlib.v1.Connection) request_;
    }
    return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ConnectionOrBuilder getCommitRequestOrBuilder() {
    if (requestCase_ == 4) {
       return (com.google.cloud.spannerlib.v1.Connection) request_;
    }
    return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
  }

  public static final int ROLLBACK_REQUEST_FIELD_NUMBER = 5;
  /**
   * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
   * @return Whether the rollbackRequest field is set.
   */
  @java.lang.Override
  public boolean hasRollbackRequest() {
    return requestCase_ == 5;
  }
  /**
   * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
   * @return The rollbackRequest.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.Connection getRollbackRequest() {
    if (requestCase_ == 5) {
       return (com.google.cloud.spannerlib.v1.Connection) request_;
    }
    return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ConnectionOrBuilder getRollbackRequestOrBuilder() {
    if (requestCase_ == 5) {
       return (com.google.cloud.spannerlib.v1.Connection) request_;
    }
    return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
  }

  public static final int WRITE_MUTATIONS_REQUEST_FIELD_NUMBER = 6;
  /**
   * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
   * @return Whether the writeMutationsRequest field is set.
   */
  @java.lang.Override
  public boolean hasWriteMutationsRequest() {
    return requestCase_ == 6;
  }
  /**
   * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
   * @return The writeMutationsRequest.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.WriteMutationsRequest getWriteMutationsRequest() {
    if (requestCase_ == 6) {
       return (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance();
  }
  /**
   * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.WriteMutationsRequestOrBuilder getWriteMutationsRequestOrBuilder() {
    if (requestCase_ == 6) {
       return (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_;
    }
    return com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (com.google.cloud.spannerlib.v1.ExecuteRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_);
    }
    if (requestCase_ == 4) {
      output.writeMessage(4, (com.google.cloud.spannerlib.v1.Connection) request_);
    }
    if (requestCase_ == 5) {
      output.writeMessage(5, (com.google.cloud.spannerlib.v1.Connection) request_);
    }
    if (requestCase_ == 6) {
      output.writeMessage(6, (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.google.cloud.spannerlib.v1.ExecuteRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_);
    }
    if (requestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.google.cloud.spannerlib.v1.Connection) request_);
    }
    if (requestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.google.cloud.spannerlib.v1.Connection) request_);
    }
    if (requestCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.spannerlib.v1.ConnectionStreamRequest)) {
      return super.equals(obj);
    }
    com.google.cloud.spannerlib.v1.ConnectionStreamRequest other = (com.google.cloud.spannerlib.v1.ConnectionStreamRequest) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getExecuteRequest()
            .equals(other.getExecuteRequest())) return false;
        break;
      case 2:
        if (!getExecuteBatchRequest()
            .equals(other.getExecuteBatchRequest())) return false;
        break;
      case 3:
        if (!getBeginTransactionRequest()
            .equals(other.getBeginTransactionRequest())) return false;
        break;
      case 4:
        if (!getCommitRequest()
            .equals(other.getCommitRequest())) return false;
        break;
      case 5:
        if (!getRollbackRequest()
            .equals(other.getRollbackRequest())) return false;
        break;
      case 6:
        if (!getWriteMutationsRequest()
            .equals(other.getWriteMutationsRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + EXECUTE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getExecuteRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + EXECUTE_BATCH_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getExecuteBatchRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + BEGIN_TRANSACTION_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getBeginTransactionRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + COMMIT_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getCommitRequest().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ROLLBACK_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRollbackRequest().hashCode();
        break;
      case 6:
        hash = (37 * hash) + WRITE_MUTATIONS_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getWriteMutationsRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.spannerlib.v1.ConnectionStreamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ConnectionStreamRequest is used by a client to send a request to the server using a
   * bi-directional gRPC stream. Such a stream is opened by calling the ConnectionStream RPC.
   * </pre>
   *
   * Protobuf type {@code google.spannerlib.v1.ConnectionStreamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.spannerlib.v1.ConnectionStreamRequest)
      com.google.cloud.spannerlib.v1.ConnectionStreamRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.spannerlib.v1.ConnectionStreamRequest.class, com.google.cloud.spannerlib.v1.ConnectionStreamRequest.Builder.class);
    }

    // Construct using com.google.cloud.spannerlib.v1.ConnectionStreamRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (executeRequestBuilder_ != null) {
        executeRequestBuilder_.clear();
      }
      if (executeBatchRequestBuilder_ != null) {
        executeBatchRequestBuilder_.clear();
      }
      if (beginTransactionRequestBuilder_ != null) {
        beginTransactionRequestBuilder_.clear();
      }
      if (commitRequestBuilder_ != null) {
        commitRequestBuilder_.clear();
      }
      if (rollbackRequestBuilder_ != null) {
        rollbackRequestBuilder_.clear();
      }
      if (writeMutationsRequestBuilder_ != null) {
        writeMutationsRequestBuilder_.clear();
      }
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_ConnectionStreamRequest_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionStreamRequest getDefaultInstanceForType() {
      return com.google.cloud.spannerlib.v1.ConnectionStreamRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionStreamRequest build() {
      com.google.cloud.spannerlib.v1.ConnectionStreamRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionStreamRequest buildPartial() {
      com.google.cloud.spannerlib.v1.ConnectionStreamRequest result = new com.google.cloud.spannerlib.v1.ConnectionStreamRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.cloud.spannerlib.v1.ConnectionStreamRequest result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.google.cloud.spannerlib.v1.ConnectionStreamRequest result) {
      result.requestCase_ = requestCase_;
      result.request_ = this.request_;
      if (requestCase_ == 1 &&
          executeRequestBuilder_ != null) {
        result.request_ = executeRequestBuilder_.build();
      }
      if (requestCase_ == 2 &&
          executeBatchRequestBuilder_ != null) {
        result.request_ = executeBatchRequestBuilder_.build();
      }
      if (requestCase_ == 3 &&
          beginTransactionRequestBuilder_ != null) {
        result.request_ = beginTransactionRequestBuilder_.build();
      }
      if (requestCase_ == 4 &&
          commitRequestBuilder_ != null) {
        result.request_ = commitRequestBuilder_.build();
      }
      if (requestCase_ == 5 &&
          rollbackRequestBuilder_ != null) {
        result.request_ = rollbackRequestBuilder_.build();
      }
      if (requestCase_ == 6 &&
          writeMutationsRequestBuilder_ != null) {
        result.request_ = writeMutationsRequestBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.spannerlib.v1.ConnectionStreamRequest) {
        return mergeFrom((com.google.cloud.spannerlib.v1.ConnectionStreamRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.spannerlib.v1.ConnectionStreamRequest other) {
      if (other == com.google.cloud.spannerlib.v1.ConnectionStreamRequest.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case EXECUTE_REQUEST: {
          mergeExecuteRequest(other.getExecuteRequest());
          break;
        }
        case EXECUTE_BATCH_REQUEST: {
          mergeExecuteBatchRequest(other.getExecuteBatchRequest());
          break;
        }
        case BEGIN_TRANSACTION_REQUEST: {
          mergeBeginTransactionRequest(other.getBeginTransactionRequest());
          break;
        }
        case COMMIT_REQUEST: {
          mergeCommitRequest(other.getCommitRequest());
          break;
        }
        case ROLLBACK_REQUEST: {
          mergeRollbackRequest(other.getRollbackRequest());
          break;
        }
        case WRITE_MUTATIONS_REQUEST: {
          mergeWriteMutationsRequest(other.getWriteMutationsRequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetExecuteRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetExecuteBatchRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetBeginTransactionRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetCommitRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetRollbackRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetWriteMutationsRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 6;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.ExecuteRequest, com.google.cloud.spannerlib.v1.ExecuteRequest.Builder, com.google.cloud.spannerlib.v1.ExecuteRequestOrBuilder> executeRequestBuilder_;
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     * @return Whether the executeRequest field is set.
     */
    @java.lang.Override
    public boolean hasExecuteRequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     * @return The executeRequest.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ExecuteRequest getExecuteRequest() {
      if (executeRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (com.google.cloud.spannerlib.v1.ExecuteRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return executeRequestBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    public Builder setExecuteRequest(com.google.cloud.spannerlib.v1.ExecuteRequest value) {
      if (executeRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        executeRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    public Builder setExecuteRequest(
        com.google.cloud.spannerlib.v1.ExecuteRequest.Builder builderForValue) {
      if (executeRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        executeRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    public Builder mergeExecuteRequest(com.google.cloud.spannerlib.v1.ExecuteRequest value) {
      if (executeRequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance()) {
          request_ = com.google.cloud.spannerlib.v1.ExecuteRequest.newBuilder((com.google.cloud.spannerlib.v1.ExecuteRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          executeRequestBuilder_.mergeFrom(value);
        } else {
          executeRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    public Builder clearExecuteRequest() {
      if (executeRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        executeRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    public com.google.cloud.spannerlib.v1.ExecuteRequest.Builder getExecuteRequestBuilder() {
      return internalGetExecuteRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ExecuteRequestOrBuilder getExecuteRequestOrBuilder() {
      if ((requestCase_ == 1) && (executeRequestBuilder_ != null)) {
        return executeRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (com.google.cloud.spannerlib.v1.ExecuteRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteRequest execute_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.ExecuteRequest, com.google.cloud.spannerlib.v1.ExecuteRequest.Builder, com.google.cloud.spannerlib.v1.ExecuteRequestOrBuilder> 
        internalGetExecuteRequestFieldBuilder() {
      if (executeRequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = com.google.cloud.spannerlib.v1.ExecuteRequest.getDefaultInstance();
        }
        executeRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.ExecuteRequest, com.google.cloud.spannerlib.v1.ExecuteRequest.Builder, com.google.cloud.spannerlib.v1.ExecuteRequestOrBuilder>(
                (com.google.cloud.spannerlib.v1.ExecuteRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();
      return executeRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.ExecuteBatchRequest, com.google.cloud.spannerlib.v1.ExecuteBatchRequest.Builder, com.google.cloud.spannerlib.v1.ExecuteBatchRequestOrBuilder> executeBatchRequestBuilder_;
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     * @return Whether the executeBatchRequest field is set.
     */
    @java.lang.Override
    public boolean hasExecuteBatchRequest() {
      return requestCase_ == 2;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     * @return The executeBatchRequest.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ExecuteBatchRequest getExecuteBatchRequest() {
      if (executeBatchRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          return (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return executeBatchRequestBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    public Builder setExecuteBatchRequest(com.google.cloud.spannerlib.v1.ExecuteBatchRequest value) {
      if (executeBatchRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        executeBatchRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    public Builder setExecuteBatchRequest(
        com.google.cloud.spannerlib.v1.ExecuteBatchRequest.Builder builderForValue) {
      if (executeBatchRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        executeBatchRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    public Builder mergeExecuteBatchRequest(com.google.cloud.spannerlib.v1.ExecuteBatchRequest value) {
      if (executeBatchRequestBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance()) {
          request_ = com.google.cloud.spannerlib.v1.ExecuteBatchRequest.newBuilder((com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          executeBatchRequestBuilder_.mergeFrom(value);
        } else {
          executeBatchRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    public Builder clearExecuteBatchRequest() {
      if (executeBatchRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        executeBatchRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    public com.google.cloud.spannerlib.v1.ExecuteBatchRequest.Builder getExecuteBatchRequestBuilder() {
      return internalGetExecuteBatchRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ExecuteBatchRequestOrBuilder getExecuteBatchRequestOrBuilder() {
      if ((requestCase_ == 2) && (executeBatchRequestBuilder_ != null)) {
        return executeBatchRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.ExecuteBatchRequest execute_batch_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.ExecuteBatchRequest, com.google.cloud.spannerlib.v1.ExecuteBatchRequest.Builder, com.google.cloud.spannerlib.v1.ExecuteBatchRequestOrBuilder> 
        internalGetExecuteBatchRequestFieldBuilder() {
      if (executeBatchRequestBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = com.google.cloud.spannerlib.v1.ExecuteBatchRequest.getDefaultInstance();
        }
        executeBatchRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.ExecuteBatchRequest, com.google.cloud.spannerlib.v1.ExecuteBatchRequest.Builder, com.google.cloud.spannerlib.v1.ExecuteBatchRequestOrBuilder>(
                (com.google.cloud.spannerlib.v1.ExecuteBatchRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();
      return executeBatchRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.BeginTransactionRequest, com.google.cloud.spannerlib.v1.BeginTransactionRequest.Builder, com.google.cloud.spannerlib.v1.BeginTransactionRequestOrBuilder> beginTransactionRequestBuilder_;
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     * @return Whether the beginTransactionRequest field is set.
     */
    @java.lang.Override
    public boolean hasBeginTransactionRequest() {
      return requestCase_ == 3;
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     * @return The beginTransactionRequest.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.BeginTransactionRequest getBeginTransactionRequest() {
      if (beginTransactionRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          return (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return beginTransactionRequestBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    public Builder setBeginTransactionRequest(com.google.cloud.spannerlib.v1.BeginTransactionRequest value) {
      if (beginTransactionRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        beginTransactionRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    public Builder setBeginTransactionRequest(
        com.google.cloud.spannerlib.v1.BeginTransactionRequest.Builder builderForValue) {
      if (beginTransactionRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        beginTransactionRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    public Builder mergeBeginTransactionRequest(com.google.cloud.spannerlib.v1.BeginTransactionRequest value) {
      if (beginTransactionRequestBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance()) {
          request_ = com.google.cloud.spannerlib.v1.BeginTransactionRequest.newBuilder((com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          beginTransactionRequestBuilder_.mergeFrom(value);
        } else {
          beginTransactionRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    public Builder clearBeginTransactionRequest() {
      if (beginTransactionRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        beginTransactionRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    public com.google.cloud.spannerlib.v1.BeginTransactionRequest.Builder getBeginTransactionRequestBuilder() {
      return internalGetBeginTransactionRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.BeginTransactionRequestOrBuilder getBeginTransactionRequestOrBuilder() {
      if ((requestCase_ == 3) && (beginTransactionRequestBuilder_ != null)) {
        return beginTransactionRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.BeginTransactionRequest begin_transaction_request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.BeginTransactionRequest, com.google.cloud.spannerlib.v1.BeginTransactionRequest.Builder, com.google.cloud.spannerlib.v1.BeginTransactionRequestOrBuilder> 
        internalGetBeginTransactionRequestFieldBuilder() {
      if (beginTransactionRequestBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = com.google.cloud.spannerlib.v1.BeginTransactionRequest.getDefaultInstance();
        }
        beginTransactionRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.BeginTransactionRequest, com.google.cloud.spannerlib.v1.BeginTransactionRequest.Builder, com.google.cloud.spannerlib.v1.BeginTransactionRequestOrBuilder>(
                (com.google.cloud.spannerlib.v1.BeginTransactionRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();
      return beginTransactionRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.Connection, com.google.cloud.spannerlib.v1.Connection.Builder, com.google.cloud.spannerlib.v1.ConnectionOrBuilder> commitRequestBuilder_;
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     * @return Whether the commitRequest field is set.
     */
    @java.lang.Override
    public boolean hasCommitRequest() {
      return requestCase_ == 4;
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     * @return The commitRequest.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.Connection getCommitRequest() {
      if (commitRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          return (com.google.cloud.spannerlib.v1.Connection) request_;
        }
        return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
      } else {
        if (requestCase_ == 4) {
          return commitRequestBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    public Builder setCommitRequest(com.google.cloud.spannerlib.v1.Connection value) {
      if (commitRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        commitRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    public Builder setCommitRequest(
        com.google.cloud.spannerlib.v1.Connection.Builder builderForValue) {
      if (commitRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        commitRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    public Builder mergeCommitRequest(com.google.cloud.spannerlib.v1.Connection value) {
      if (commitRequestBuilder_ == null) {
        if (requestCase_ == 4 &&
            request_ != com.google.cloud.spannerlib.v1.Connection.getDefaultInstance()) {
          request_ = com.google.cloud.spannerlib.v1.Connection.newBuilder((com.google.cloud.spannerlib.v1.Connection) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 4) {
          commitRequestBuilder_.mergeFrom(value);
        } else {
          commitRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    public Builder clearCommitRequest() {
      if (commitRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
        }
        commitRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    public com.google.cloud.spannerlib.v1.Connection.Builder getCommitRequestBuilder() {
      return internalGetCommitRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionOrBuilder getCommitRequestOrBuilder() {
      if ((requestCase_ == 4) && (commitRequestBuilder_ != null)) {
        return commitRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 4) {
          return (com.google.cloud.spannerlib.v1.Connection) request_;
        }
        return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.Connection commit_request = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.Connection, com.google.cloud.spannerlib.v1.Connection.Builder, com.google.cloud.spannerlib.v1.ConnectionOrBuilder> 
        internalGetCommitRequestFieldBuilder() {
      if (commitRequestBuilder_ == null) {
        if (!(requestCase_ == 4)) {
          request_ = com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
        }
        commitRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.Connection, com.google.cloud.spannerlib.v1.Connection.Builder, com.google.cloud.spannerlib.v1.ConnectionOrBuilder>(
                (com.google.cloud.spannerlib.v1.Connection) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 4;
      onChanged();
      return commitRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.Connection, com.google.cloud.spannerlib.v1.Connection.Builder, com.google.cloud.spannerlib.v1.ConnectionOrBuilder> rollbackRequestBuilder_;
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     * @return Whether the rollbackRequest field is set.
     */
    @java.lang.Override
    public boolean hasRollbackRequest() {
      return requestCase_ == 5;
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     * @return The rollbackRequest.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.Connection getRollbackRequest() {
      if (rollbackRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          return (com.google.cloud.spannerlib.v1.Connection) request_;
        }
        return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
      } else {
        if (requestCase_ == 5) {
          return rollbackRequestBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    public Builder setRollbackRequest(com.google.cloud.spannerlib.v1.Connection value) {
      if (rollbackRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        rollbackRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    public Builder setRollbackRequest(
        com.google.cloud.spannerlib.v1.Connection.Builder builderForValue) {
      if (rollbackRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        rollbackRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    public Builder mergeRollbackRequest(com.google.cloud.spannerlib.v1.Connection value) {
      if (rollbackRequestBuilder_ == null) {
        if (requestCase_ == 5 &&
            request_ != com.google.cloud.spannerlib.v1.Connection.getDefaultInstance()) {
          request_ = com.google.cloud.spannerlib.v1.Connection.newBuilder((com.google.cloud.spannerlib.v1.Connection) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 5) {
          rollbackRequestBuilder_.mergeFrom(value);
        } else {
          rollbackRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    public Builder clearRollbackRequest() {
      if (rollbackRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
        }
        rollbackRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    public com.google.cloud.spannerlib.v1.Connection.Builder getRollbackRequestBuilder() {
      return internalGetRollbackRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.ConnectionOrBuilder getRollbackRequestOrBuilder() {
      if ((requestCase_ == 5) && (rollbackRequestBuilder_ != null)) {
        return rollbackRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 5) {
          return (com.google.cloud.spannerlib.v1.Connection) request_;
        }
        return com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.Connection rollback_request = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.Connection, com.google.cloud.spannerlib.v1.Connection.Builder, com.google.cloud.spannerlib.v1.ConnectionOrBuilder> 
        internalGetRollbackRequestFieldBuilder() {
      if (rollbackRequestBuilder_ == null) {
        if (!(requestCase_ == 5)) {
          request_ = com.google.cloud.spannerlib.v1.Connection.getDefaultInstance();
        }
        rollbackRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.Connection, com.google.cloud.spannerlib.v1.Connection.Builder, com.google.cloud.spannerlib.v1.ConnectionOrBuilder>(
                (com.google.cloud.spannerlib.v1.Connection) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 5;
      onChanged();
      return rollbackRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.WriteMutationsRequest, com.google.cloud.spannerlib.v1.WriteMutationsRequest.Builder, com.google.cloud.spannerlib.v1.WriteMutationsRequestOrBuilder> writeMutationsRequestBuilder_;
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     * @return Whether the writeMutationsRequest field is set.
     */
    @java.lang.Override
    public boolean hasWriteMutationsRequest() {
      return requestCase_ == 6;
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     * @return The writeMutationsRequest.
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.WriteMutationsRequest getWriteMutationsRequest() {
      if (writeMutationsRequestBuilder_ == null) {
        if (requestCase_ == 6) {
          return (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 6) {
          return writeMutationsRequestBuilder_.getMessage();
        }
        return com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    public Builder setWriteMutationsRequest(com.google.cloud.spannerlib.v1.WriteMutationsRequest value) {
      if (writeMutationsRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        writeMutationsRequestBuilder_.setMessage(value);
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    public Builder setWriteMutationsRequest(
        com.google.cloud.spannerlib.v1.WriteMutationsRequest.Builder builderForValue) {
      if (writeMutationsRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        writeMutationsRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    public Builder mergeWriteMutationsRequest(com.google.cloud.spannerlib.v1.WriteMutationsRequest value) {
      if (writeMutationsRequestBuilder_ == null) {
        if (requestCase_ == 6 &&
            request_ != com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance()) {
          request_ = com.google.cloud.spannerlib.v1.WriteMutationsRequest.newBuilder((com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 6) {
          writeMutationsRequestBuilder_.mergeFrom(value);
        } else {
          writeMutationsRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    public Builder clearWriteMutationsRequest() {
      if (writeMutationsRequestBuilder_ == null) {
        if (requestCase_ == 6) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 6) {
          requestCase_ = 0;
          request_ = null;
        }
        writeMutationsRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    public com.google.cloud.spannerlib.v1.WriteMutationsRequest.Builder getWriteMutationsRequestBuilder() {
      return internalGetWriteMutationsRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    @java.lang.Override
    public com.google.cloud.spannerlib.v1.WriteMutationsRequestOrBuilder getWriteMutationsRequestOrBuilder() {
      if ((requestCase_ == 6) && (writeMutationsRequestBuilder_ != null)) {
        return writeMutationsRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 6) {
          return (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_;
        }
        return com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.google.spannerlib.v1.WriteMutationsRequest write_mutations_request = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.WriteMutationsRequest, com.google.cloud.spannerlib.v1.WriteMutationsRequest.Builder, com.google.cloud.spannerlib.v1.WriteMutationsRequestOrBuilder> 
        internalGetWriteMutationsRequestFieldBuilder() {
      if (writeMutationsRequestBuilder_ == null) {
        if (!(requestCase_ == 6)) {
          request_ = com.google.cloud.spannerlib.v1.WriteMutationsRequest.getDefaultInstance();
        }
        writeMutationsRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.WriteMutationsRequest, com.google.cloud.spannerlib.v1.WriteMutationsRequest.Builder, com.google.cloud.spannerlib.v1.WriteMutationsRequestOrBuilder>(
                (com.google.cloud.spannerlib.v1.WriteMutationsRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 6;
      onChanged();
      return writeMutationsRequestBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.spannerlib.v1.ConnectionStreamRequest)
  }

  // @@protoc_insertion_point(class_scope:google.spannerlib.v1.ConnectionStreamRequest)
  private static final com.google.cloud.spannerlib.v1.ConnectionStreamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.spannerlib.v1.ConnectionStreamRequest();
  }

  public static com.google.cloud.spannerlib.v1.ConnectionStreamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConnectionStreamRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConnectionStreamRequest>() {
    @java.lang.Override
    public ConnectionStreamRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConnectionStreamRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConnectionStreamRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.spannerlib.v1.ConnectionStreamRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

