// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

@com.google.protobuf.Generated
public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.spannerlib.v1.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the rows field is set.
   */
  boolean hasRows();
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The rows.
   */
  com.google.cloud.spannerlib.v1.Rows getRows();
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.spannerlib.v1.RowsOrBuilder getRowsOrBuilder();

  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 2;</code>
   */
  java.util.List<com.google.spanner.v1.ResultSet> 
      getResultSetsList();
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 2;</code>
   */
  com.google.spanner.v1.ResultSet getResultSets(int index);
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 2;</code>
   */
  int getResultSetsCount();
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 2;</code>
   */
  java.util.List<? extends com.google.spanner.v1.ResultSetOrBuilder> 
      getResultSetsOrBuilderList();
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 2;</code>
   */
  com.google.spanner.v1.ResultSetOrBuilder getResultSetsOrBuilder(
      int index);

  /**
   * <code>.google.rpc.Status status = 3;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.google.rpc.Status status = 3;</code>
   * @return The status.
   */
  com.google.rpc.Status getStatus();
  /**
   * <code>.google.rpc.Status status = 3;</code>
   */
  com.google.rpc.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>bool has_more_results = 4;</code>
   * @return The hasMoreResults.
   */
  boolean getHasMoreResults();
}
