// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

@com.google.protobuf.Generated
public interface ExecuteAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.spannerlib.v1.ExecuteAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 1;</code>
   */
  java.util.List<com.google.spanner.v1.ResultSet> 
      getResultSetsList();
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 1;</code>
   */
  com.google.spanner.v1.ResultSet getResultSets(int index);
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 1;</code>
   */
  int getResultSetsCount();
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 1;</code>
   */
  java.util.List<? extends com.google.spanner.v1.ResultSetOrBuilder> 
      getResultSetsOrBuilderList();
  /**
   * <code>repeated .google.spanner.v1.ResultSet result_sets = 1;</code>
   */
  com.google.spanner.v1.ResultSetOrBuilder getResultSetsOrBuilder(
      int index);
}
