// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

/**
 * Protobuf type {@code google.spannerlib.v1.FetchOptions}
 */
@com.google.protobuf.Generated
public final class FetchOptions extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.spannerlib.v1.FetchOptions)
    FetchOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      FetchOptions.class.getName());
  }
  // Use FetchOptions.newBuilder() to construct.
  private FetchOptions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FetchOptions() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_FetchOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_FetchOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.spannerlib.v1.FetchOptions.class, com.google.cloud.spannerlib.v1.FetchOptions.Builder.class);
  }

  public static final int NUM_ROWS_FIELD_NUMBER = 1;
  private long numRows_ = 0L;
  /**
   * <code>int64 num_rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The numRows.
   */
  @java.lang.Override
  public long getNumRows() {
    return numRows_;
  }

  public static final int ENCODING_FIELD_NUMBER = 2;
  private long encoding_ = 0L;
  /**
   * <code>int64 encoding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The encoding.
   */
  @java.lang.Override
  public long getEncoding() {
    return encoding_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numRows_ != 0L) {
      output.writeInt64(1, numRows_);
    }
    if (encoding_ != 0L) {
      output.writeInt64(2, encoding_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numRows_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, numRows_);
    }
    if (encoding_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, encoding_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.spannerlib.v1.FetchOptions)) {
      return super.equals(obj);
    }
    com.google.cloud.spannerlib.v1.FetchOptions other = (com.google.cloud.spannerlib.v1.FetchOptions) obj;

    if (getNumRows()
        != other.getNumRows()) return false;
    if (getEncoding()
        != other.getEncoding()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUM_ROWS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumRows());
    hash = (37 * hash) + ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEncoding());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.spannerlib.v1.FetchOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.spannerlib.v1.FetchOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.FetchOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.spannerlib.v1.FetchOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.spannerlib.v1.FetchOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.spannerlib.v1.FetchOptions)
      com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_FetchOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_FetchOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.spannerlib.v1.FetchOptions.class, com.google.cloud.spannerlib.v1.FetchOptions.Builder.class);
    }

    // Construct using com.google.cloud.spannerlib.v1.FetchOptions.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numRows_ = 0L;
      encoding_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_FetchOptions_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.FetchOptions getDefaultInstanceForType() {
      return com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.FetchOptions build() {
      com.google.cloud.spannerlib.v1.FetchOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.FetchOptions buildPartial() {
      com.google.cloud.spannerlib.v1.FetchOptions result = new com.google.cloud.spannerlib.v1.FetchOptions(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.cloud.spannerlib.v1.FetchOptions result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numRows_ = numRows_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.encoding_ = encoding_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.spannerlib.v1.FetchOptions) {
        return mergeFrom((com.google.cloud.spannerlib.v1.FetchOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.spannerlib.v1.FetchOptions other) {
      if (other == com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance()) return this;
      if (other.getNumRows() != 0L) {
        setNumRows(other.getNumRows());
      }
      if (other.getEncoding() != 0L) {
        setEncoding(other.getEncoding());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numRows_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              encoding_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long numRows_ ;
    /**
     * <code>int64 num_rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The numRows.
     */
    @java.lang.Override
    public long getNumRows() {
      return numRows_;
    }
    /**
     * <code>int64 num_rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The numRows to set.
     * @return This builder for chaining.
     */
    public Builder setNumRows(long value) {

      numRows_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 num_rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumRows() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numRows_ = 0L;
      onChanged();
      return this;
    }

    private long encoding_ ;
    /**
     * <code>int64 encoding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The encoding.
     */
    @java.lang.Override
    public long getEncoding() {
      return encoding_;
    }
    /**
     * <code>int64 encoding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncoding(long value) {

      encoding_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 encoding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearEncoding() {
      bitField0_ = (bitField0_ & ~0x00000002);
      encoding_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.spannerlib.v1.FetchOptions)
  }

  // @@protoc_insertion_point(class_scope:google.spannerlib.v1.FetchOptions)
  private static final com.google.cloud.spannerlib.v1.FetchOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.spannerlib.v1.FetchOptions();
  }

  public static com.google.cloud.spannerlib.v1.FetchOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchOptions>
      PARSER = new com.google.protobuf.AbstractParser<FetchOptions>() {
    @java.lang.Override
    public FetchOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.spannerlib.v1.FetchOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

