// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

@com.google.protobuf.Generated
public interface FetchOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.spannerlib.v1.FetchOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 num_rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The numRows.
   */
  long getNumRows();

  /**
   * <code>int64 encoding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The encoding.
   */
  long getEncoding();
}
