// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

/**
 * Protobuf type {@code google.spannerlib.v1.NextRequest}
 */
@com.google.protobuf.Generated
public final class NextRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.spannerlib.v1.NextRequest)
    NextRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      NextRequest.class.getName());
  }
  // Use NextRequest.newBuilder() to construct.
  private NextRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NextRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_NextRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_NextRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.spannerlib.v1.NextRequest.class, com.google.cloud.spannerlib.v1.NextRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ROWS_FIELD_NUMBER = 1;
  private com.google.cloud.spannerlib.v1.Rows rows_;
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the rows field is set.
   */
  @java.lang.Override
  public boolean hasRows() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The rows.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.Rows getRows() {
    return rows_ == null ? com.google.cloud.spannerlib.v1.Rows.getDefaultInstance() : rows_;
  }
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.RowsOrBuilder getRowsOrBuilder() {
    return rows_ == null ? com.google.cloud.spannerlib.v1.Rows.getDefaultInstance() : rows_;
  }

  public static final int FETCH_OPTIONS_FIELD_NUMBER = 2;
  private com.google.cloud.spannerlib.v1.FetchOptions fetchOptions_;
  /**
   * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the fetchOptions field is set.
   */
  @java.lang.Override
  public boolean hasFetchOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The fetchOptions.
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.FetchOptions getFetchOptions() {
    return fetchOptions_ == null ? com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance() : fetchOptions_;
  }
  /**
   * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder getFetchOptionsOrBuilder() {
    return fetchOptions_ == null ? com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance() : fetchOptions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRows());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getFetchOptions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRows());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFetchOptions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.spannerlib.v1.NextRequest)) {
      return super.equals(obj);
    }
    com.google.cloud.spannerlib.v1.NextRequest other = (com.google.cloud.spannerlib.v1.NextRequest) obj;

    if (hasRows() != other.hasRows()) return false;
    if (hasRows()) {
      if (!getRows()
          .equals(other.getRows())) return false;
    }
    if (hasFetchOptions() != other.hasFetchOptions()) return false;
    if (hasFetchOptions()) {
      if (!getFetchOptions()
          .equals(other.getFetchOptions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRows()) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRows().hashCode();
    }
    if (hasFetchOptions()) {
      hash = (37 * hash) + FETCH_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFetchOptions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.spannerlib.v1.NextRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.spannerlib.v1.NextRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.spannerlib.v1.NextRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.spannerlib.v1.NextRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.spannerlib.v1.NextRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.spannerlib.v1.NextRequest)
      com.google.cloud.spannerlib.v1.NextRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_NextRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_NextRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.spannerlib.v1.NextRequest.class, com.google.cloud.spannerlib.v1.NextRequest.Builder.class);
    }

    // Construct using com.google.cloud.spannerlib.v1.NextRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRowsFieldBuilder();
        internalGetFetchOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rows_ = null;
      if (rowsBuilder_ != null) {
        rowsBuilder_.dispose();
        rowsBuilder_ = null;
      }
      fetchOptions_ = null;
      if (fetchOptionsBuilder_ != null) {
        fetchOptionsBuilder_.dispose();
        fetchOptionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.spannerlib.v1.SpannerLibProto.internal_static_google_spannerlib_v1_NextRequest_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.NextRequest getDefaultInstanceForType() {
      return com.google.cloud.spannerlib.v1.NextRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.NextRequest build() {
      com.google.cloud.spannerlib.v1.NextRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.spannerlib.v1.NextRequest buildPartial() {
      com.google.cloud.spannerlib.v1.NextRequest result = new com.google.cloud.spannerlib.v1.NextRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.cloud.spannerlib.v1.NextRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rows_ = rowsBuilder_ == null
            ? rows_
            : rowsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fetchOptions_ = fetchOptionsBuilder_ == null
            ? fetchOptions_
            : fetchOptionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.spannerlib.v1.NextRequest) {
        return mergeFrom((com.google.cloud.spannerlib.v1.NextRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.spannerlib.v1.NextRequest other) {
      if (other == com.google.cloud.spannerlib.v1.NextRequest.getDefaultInstance()) return this;
      if (other.hasRows()) {
        mergeRows(other.getRows());
      }
      if (other.hasFetchOptions()) {
        mergeFetchOptions(other.getFetchOptions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRowsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetFetchOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.cloud.spannerlib.v1.Rows rows_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.Rows, com.google.cloud.spannerlib.v1.Rows.Builder, com.google.cloud.spannerlib.v1.RowsOrBuilder> rowsBuilder_;
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the rows field is set.
     */
    public boolean hasRows() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The rows.
     */
    public com.google.cloud.spannerlib.v1.Rows getRows() {
      if (rowsBuilder_ == null) {
        return rows_ == null ? com.google.cloud.spannerlib.v1.Rows.getDefaultInstance() : rows_;
      } else {
        return rowsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setRows(com.google.cloud.spannerlib.v1.Rows value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rows_ = value;
      } else {
        rowsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setRows(
        com.google.cloud.spannerlib.v1.Rows.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        rows_ = builderForValue.build();
      } else {
        rowsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeRows(com.google.cloud.spannerlib.v1.Rows value) {
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          rows_ != null &&
          rows_ != com.google.cloud.spannerlib.v1.Rows.getDefaultInstance()) {
          getRowsBuilder().mergeFrom(value);
        } else {
          rows_ = value;
        }
      } else {
        rowsBuilder_.mergeFrom(value);
      }
      if (rows_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearRows() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rows_ = null;
      if (rowsBuilder_ != null) {
        rowsBuilder_.dispose();
        rowsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.cloud.spannerlib.v1.Rows.Builder getRowsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetRowsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.cloud.spannerlib.v1.RowsOrBuilder getRowsOrBuilder() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilder();
      } else {
        return rows_ == null ?
            com.google.cloud.spannerlib.v1.Rows.getDefaultInstance() : rows_;
      }
    }
    /**
     * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.Rows, com.google.cloud.spannerlib.v1.Rows.Builder, com.google.cloud.spannerlib.v1.RowsOrBuilder> 
        internalGetRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.Rows, com.google.cloud.spannerlib.v1.Rows.Builder, com.google.cloud.spannerlib.v1.RowsOrBuilder>(
                getRows(),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }

    private com.google.cloud.spannerlib.v1.FetchOptions fetchOptions_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.FetchOptions, com.google.cloud.spannerlib.v1.FetchOptions.Builder, com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder> fetchOptionsBuilder_;
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the fetchOptions field is set.
     */
    public boolean hasFetchOptions() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The fetchOptions.
     */
    public com.google.cloud.spannerlib.v1.FetchOptions getFetchOptions() {
      if (fetchOptionsBuilder_ == null) {
        return fetchOptions_ == null ? com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance() : fetchOptions_;
      } else {
        return fetchOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setFetchOptions(com.google.cloud.spannerlib.v1.FetchOptions value) {
      if (fetchOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fetchOptions_ = value;
      } else {
        fetchOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setFetchOptions(
        com.google.cloud.spannerlib.v1.FetchOptions.Builder builderForValue) {
      if (fetchOptionsBuilder_ == null) {
        fetchOptions_ = builderForValue.build();
      } else {
        fetchOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeFetchOptions(com.google.cloud.spannerlib.v1.FetchOptions value) {
      if (fetchOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          fetchOptions_ != null &&
          fetchOptions_ != com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance()) {
          getFetchOptionsBuilder().mergeFrom(value);
        } else {
          fetchOptions_ = value;
        }
      } else {
        fetchOptionsBuilder_.mergeFrom(value);
      }
      if (fetchOptions_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearFetchOptions() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fetchOptions_ = null;
      if (fetchOptionsBuilder_ != null) {
        fetchOptionsBuilder_.dispose();
        fetchOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.cloud.spannerlib.v1.FetchOptions.Builder getFetchOptionsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetFetchOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder getFetchOptionsOrBuilder() {
      if (fetchOptionsBuilder_ != null) {
        return fetchOptionsBuilder_.getMessageOrBuilder();
      } else {
        return fetchOptions_ == null ?
            com.google.cloud.spannerlib.v1.FetchOptions.getDefaultInstance() : fetchOptions_;
      }
    }
    /**
     * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.cloud.spannerlib.v1.FetchOptions, com.google.cloud.spannerlib.v1.FetchOptions.Builder, com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder> 
        internalGetFetchOptionsFieldBuilder() {
      if (fetchOptionsBuilder_ == null) {
        fetchOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.cloud.spannerlib.v1.FetchOptions, com.google.cloud.spannerlib.v1.FetchOptions.Builder, com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder>(
                getFetchOptions(),
                getParentForChildren(),
                isClean());
        fetchOptions_ = null;
      }
      return fetchOptionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.spannerlib.v1.NextRequest)
  }

  // @@protoc_insertion_point(class_scope:google.spannerlib.v1.NextRequest)
  private static final com.google.cloud.spannerlib.v1.NextRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.spannerlib.v1.NextRequest();
  }

  public static com.google.cloud.spannerlib.v1.NextRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NextRequest>
      PARSER = new com.google.protobuf.AbstractParser<NextRequest>() {
    @java.lang.Override
    public NextRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NextRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NextRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.spannerlib.v1.NextRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

