// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

@com.google.protobuf.Generated
public interface NextRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.spannerlib.v1.NextRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the rows field is set.
   */
  boolean hasRows();
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The rows.
   */
  com.google.cloud.spannerlib.v1.Rows getRows();
  /**
   * <code>.google.spannerlib.v1.Rows rows = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.spannerlib.v1.RowsOrBuilder getRowsOrBuilder();

  /**
   * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the fetchOptions field is set.
   */
  boolean hasFetchOptions();
  /**
   * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The fetchOptions.
   */
  com.google.cloud.spannerlib.v1.FetchOptions getFetchOptions();
  /**
   * <code>.google.spannerlib.v1.FetchOptions fetch_options = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.spannerlib.v1.FetchOptionsOrBuilder getFetchOptionsOrBuilder();
}
