// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spannerlib/v1/spannerlib.proto
// Protobuf Java Version: 4.32.1

package com.google.cloud.spannerlib.v1;

@com.google.protobuf.Generated
public final class SpannerLibProto extends com.google.protobuf.GeneratedFile {
  private SpannerLibProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      SpannerLibProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_InfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_InfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_InfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_CreatePoolRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_CreatePoolRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_CreateConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_CreateConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_ExecuteBatchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_ExecuteBatchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_BeginTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_BeginTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_WriteMutationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_WriteMutationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_Pool_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_Pool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_Connection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_Connection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_Rows_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_Rows_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_NextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_NextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_FetchOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_FetchOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_RowData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_RowData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_MetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_MetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_ResultSetStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_ResultSetStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_ConnectionStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_ConnectionStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spannerlib_v1_ConnectionStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_spannerlib_v1_ConnectionStreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%google/spannerlib/v1/spannerlib.proto\022" +
      "\024google.spannerlib.v1\032\037google/api/field_" +
      "behavior.proto\032\033google/protobuf/empty.pr" +
      "oto\032\034google/protobuf/struct.proto\032\027googl" +
      "e/rpc/status.proto\032\"google/spanner/v1/re" +
      "sult_set.proto\032\037google/spanner/v1/spanne" +
      "r.proto\032#google/spanner/v1/transaction.p" +
      "roto\"\r\n\013InfoRequest\"\037\n\014InfoResponse\022\017\n\007v" +
      "ersion\030\001 \001(\t\"3\n\021CreatePoolRequest\022\036\n\021con" +
      "nection_string\030\001 \001(\tB\003\340A\002\"H\n\027CreateConne" +
      "ctionRequest\022-\n\004pool\030\001 \001(\0132\032.google.span" +
      "nerlib.v1.PoolB\003\340A\002\"\316\001\n\016ExecuteRequest\0229" +
      "\n\nconnection\030\001 \001(\0132 .google.spannerlib.v" +
      "1.ConnectionB\003\340A\002\022F\n\023execute_sql_request" +
      "\030\002 \001(\0132$.google.spanner.v1.ExecuteSqlReq" +
      "uestB\003\340A\002\0229\n\rfetch_options\030\003 \001(\0132\".googl" +
      "e.spannerlib.v1.FetchOptions\"\243\001\n\023Execute" +
      "BatchRequest\0229\n\nconnection\030\001 \001(\0132 .googl" +
      "e.spannerlib.v1.ConnectionB\003\340A\002\022Q\n\031execu" +
      "te_batch_dml_request\030\002 \001(\0132).google.span" +
      "ner.v1.ExecuteBatchDmlRequestB\003\340A\002\"\235\001\n\027B" +
      "eginTransactionRequest\0229\n\nconnection\030\001 \001" +
      "(\0132 .google.spannerlib.v1.ConnectionB\003\340A" +
      "\002\022G\n\023transaction_options\030\002 \001(\0132%.google." +
      "spanner.v1.TransactionOptionsB\003\340A\002\"\236\001\n\025W" +
      "riteMutationsRequest\0229\n\nconnection\030\001 \001(\013" +
      "2 .google.spannerlib.v1.ConnectionB\003\340A\002\022" +
      "J\n\tmutations\030\002 \001(\01322.google.spanner.v1.B" +
      "atchWriteRequest.MutationGroupB\003\340A\002\"\027\n\004P" +
      "ool\022\017\n\002id\030\001 \001(\003B\003\340A\002\"L\n\nConnection\022-\n\004po" +
      "ol\030\001 \001(\0132\032.google.spannerlib.v1.PoolB\003\340A" +
      "\002\022\017\n\002id\030\002 \001(\003B\003\340A\002\"R\n\004Rows\0229\n\nconnection" +
      "\030\001 \001(\0132 .google.spannerlib.v1.Connection" +
      "B\003\340A\002\022\017\n\002id\030\002 \001(\003B\003\340A\002\"|\n\013NextRequest\022-\n" +
      "\004rows\030\001 \001(\0132\032.google.spannerlib.v1.RowsB" +
      "\003\340A\002\022>\n\rfetch_options\030\002 \001(\0132\".google.spa" +
      "nnerlib.v1.FetchOptionsB\003\340A\002\"<\n\014FetchOpt" +
      "ions\022\025\n\010num_rows\030\001 \001(\003B\003\340A\002\022\025\n\010encoding\030" +
      "\002 \001(\003B\003\340A\002\"\377\001\n\007RowData\022\022\n\nrequest_id\030\001 \001" +
      "(\t\022-\n\004rows\030\002 \001(\0132\032.google.spannerlib.v1." +
      "RowsB\003\340A\002\0226\n\010metadata\030\003 \001(\0132$.google.spa" +
      "nner.v1.ResultSetMetadata\022-\n\004data\030\004 \003(\0132" +
      "\032.google.protobuf.ListValueB\003\340A\002\0220\n\005stat" +
      "s\030\005 \001(\0132!.google.spanner.v1.ResultSetSta" +
      "ts\022\030\n\020has_more_results\030\006 \001(\010\"@\n\017Metadata" +
      "Request\022-\n\004rows\030\001 \001(\0132\032.google.spannerli" +
      "b.v1.RowsB\003\340A\002\"F\n\025ResultSetStatsRequest\022" +
      "-\n\004rows\030\001 \001(\0132\032.google.spannerlib.v1.Row" +
      "sB\003\340A\002\"\317\003\n\027ConnectionStreamRequest\022?\n\017ex" +
      "ecute_request\030\001 \001(\0132$.google.spannerlib." +
      "v1.ExecuteRequestH\000\022J\n\025execute_batch_req" +
      "uest\030\002 \001(\0132).google.spannerlib.v1.Execut" +
      "eBatchRequestH\000\022R\n\031begin_transaction_req" +
      "uest\030\003 \001(\0132-.google.spannerlib.v1.BeginT" +
      "ransactionRequestH\000\022:\n\016commit_request\030\004 " +
      "\001(\0132 .google.spannerlib.v1.ConnectionH\000\022" +
      "<\n\020rollback_request\030\005 \001(\0132 .google.spann" +
      "erlib.v1.ConnectionH\000\022N\n\027write_mutations" +
      "_request\030\006 \001(\0132+.google.spannerlib.v1.Wr" +
      "iteMutationsRequestH\000B\t\n\007request\"\261\001\n\017Exe" +
      "cuteResponse\022-\n\004rows\030\001 \001(\0132\032.google.span" +
      "nerlib.v1.RowsB\003\340A\002\0221\n\013result_sets\030\002 \003(\013" +
      "2\034.google.spanner.v1.ResultSet\022\"\n\006status" +
      "\030\003 \001(\0132\022.google.rpc.Status\022\030\n\020has_more_r" +
      "esults\030\004 \001(\010\"\323\003\n\030ConnectionStreamRespons" +
      "e\022\"\n\006status\030\001 \001(\0132\022.google.rpc.Status\022A\n" +
      "\020execute_response\030\002 \001(\0132%.google.spanner" +
      "lib.v1.ExecuteResponseH\000\022L\n\026execute_batc" +
      "h_response\030\003 \001(\0132*.google.spanner.v1.Exe" +
      "cuteBatchDmlResponseH\000\022<\n\032begin_transact" +
      "ion_response\030\004 \001(\0132\026.google.protobuf.Emp" +
      "tyH\000\022<\n\017commit_response\030\005 \001(\0132!.google.s" +
      "panner.v1.CommitResponseH\000\0223\n\021rollback_r" +
      "esponse\030\006 \001(\0132\026.google.protobuf.EmptyH\000\022" +
      "E\n\030write_mutations_response\030\007 \001(\0132!.goog" +
      "le.spanner.v1.CommitResponseH\000B\n\n\010respon" +
      "se2\353\014\n\nSpannerLib\022O\n\004Info\022!.google.spann" +
      "erlib.v1.InfoRequest\032\".google.spannerlib" +
      ".v1.InfoResponse\"\000\022S\n\nCreatePool\022\'.googl" +
      "e.spannerlib.v1.CreatePoolRequest\032\032.goog" +
      "le.spannerlib.v1.Pool\"\000\022A\n\tClosePool\022\032.g" +
      "oogle.spannerlib.v1.Pool\032\026.google.protob" +
      "uf.Empty\"\000\022e\n\020CreateConnection\022-.google." +
      "spannerlib.v1.CreateConnectionRequest\032 ." +
      "google.spannerlib.v1.Connection\"\000\022M\n\017Clo" +
      "seConnection\022 .google.spannerlib.v1.Conn" +
      "ection\032\026.google.protobuf.Empty\"\000\022M\n\007Exec" +
      "ute\022$.google.spannerlib.v1.ExecuteReques" +
      "t\032\032.google.spannerlib.v1.Rows\"\000\022[\n\020Execu" +
      "teStreaming\022$.google.spannerlib.v1.Execu" +
      "teRequest\032\035.google.spannerlib.v1.RowData" +
      "\"\0000\001\022g\n\014ExecuteBatch\022).google.spannerlib" +
      ".v1.ExecuteBatchRequest\032*.google.spanner" +
      ".v1.ExecuteBatchDmlResponse\"\000\022N\n\010Metadat" +
      "a\022\032.google.spannerlib.v1.Rows\032$.google.s" +
      "panner.v1.ResultSetMetadata\"\000\022G\n\004Next\022!." +
      "google.spannerlib.v1.NextRequest\032\032.googl" +
      "e.protobuf.ListValue\"\000\022Q\n\016ResultSetStats" +
      "\022\032.google.spannerlib.v1.Rows\032!.google.sp" +
      "anner.v1.ResultSetStats\"\000\022S\n\rNextResultS" +
      "et\022\032.google.spannerlib.v1.Rows\032$.google." +
      "spanner.v1.ResultSetMetadata\"\000\022A\n\tCloseR" +
      "ows\022\032.google.spannerlib.v1.Rows\032\026.google" +
      ".protobuf.Empty\"\000\022[\n\020BeginTransaction\022-." +
      "google.spannerlib.v1.BeginTransactionReq" +
      "uest\032\026.google.protobuf.Empty\"\000\022O\n\006Commit" +
      "\022 .google.spannerlib.v1.Connection\032!.goo" +
      "gle.spanner.v1.CommitResponse\"\000\022F\n\010Rollb" +
      "ack\022 .google.spannerlib.v1.Connection\032\026." +
      "google.protobuf.Empty\"\000\022b\n\016WriteMutation" +
      "s\022+.google.spannerlib.v1.WriteMutationsR" +
      "equest\032!.google.spanner.v1.CommitRespons" +
      "e\"\000\022w\n\020ConnectionStream\022-.google.spanner" +
      "lib.v1.ConnectionStreamRequest\032..google." +
      "spannerlib.v1.ConnectionStreamResponse\"\000" +
      "(\0010\001\022R\n\021ContinueStreaming\022\032.google.spann" +
      "erlib.v1.Rows\032\035.google.spannerlib.v1.Row" +
      "Data\"\0000\001B\315\001\n\036com.google.cloud.spannerlib" +
      ".v1B\017SpannerLibProtoP\001Z>cloud.google.com" +
      "/go/spannerlib/apiv1/spannerlibpb;spanne" +
      "rlibpb\252\002\032Google.Cloud.SpannerLib.V1\312\002\032Go" +
      "ogle\\Cloud\\SpannerLib\\V1\352\002\035Google::Cloud" +
      "::SpannerLib::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
          com.google.spanner.v1.ResultSetProto.getDescriptor(),
          com.google.spanner.v1.SpannerProto.getDescriptor(),
          com.google.spanner.v1.TransactionProto.getDescriptor(),
        });
    internal_static_google_spannerlib_v1_InfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_spannerlib_v1_InfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_InfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_google_spannerlib_v1_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_spannerlib_v1_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_InfoResponse_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_google_spannerlib_v1_CreatePoolRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_spannerlib_v1_CreatePoolRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_CreatePoolRequest_descriptor,
        new java.lang.String[] { "ConnectionString", });
    internal_static_google_spannerlib_v1_CreateConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_spannerlib_v1_CreateConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_CreateConnectionRequest_descriptor,
        new java.lang.String[] { "Pool", });
    internal_static_google_spannerlib_v1_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_spannerlib_v1_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_ExecuteRequest_descriptor,
        new java.lang.String[] { "Connection", "ExecuteSqlRequest", "FetchOptions", });
    internal_static_google_spannerlib_v1_ExecuteBatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_spannerlib_v1_ExecuteBatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_ExecuteBatchRequest_descriptor,
        new java.lang.String[] { "Connection", "ExecuteBatchDmlRequest", });
    internal_static_google_spannerlib_v1_BeginTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_spannerlib_v1_BeginTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_BeginTransactionRequest_descriptor,
        new java.lang.String[] { "Connection", "TransactionOptions", });
    internal_static_google_spannerlib_v1_WriteMutationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_spannerlib_v1_WriteMutationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_WriteMutationsRequest_descriptor,
        new java.lang.String[] { "Connection", "Mutations", });
    internal_static_google_spannerlib_v1_Pool_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_spannerlib_v1_Pool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_Pool_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_google_spannerlib_v1_Connection_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_spannerlib_v1_Connection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_Connection_descriptor,
        new java.lang.String[] { "Pool", "Id", });
    internal_static_google_spannerlib_v1_Rows_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_spannerlib_v1_Rows_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_Rows_descriptor,
        new java.lang.String[] { "Connection", "Id", });
    internal_static_google_spannerlib_v1_NextRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_spannerlib_v1_NextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_NextRequest_descriptor,
        new java.lang.String[] { "Rows", "FetchOptions", });
    internal_static_google_spannerlib_v1_FetchOptions_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_spannerlib_v1_FetchOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_FetchOptions_descriptor,
        new java.lang.String[] { "NumRows", "Encoding", });
    internal_static_google_spannerlib_v1_RowData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_spannerlib_v1_RowData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_RowData_descriptor,
        new java.lang.String[] { "RequestId", "Rows", "Metadata", "Data", "Stats", "HasMoreResults", });
    internal_static_google_spannerlib_v1_MetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_spannerlib_v1_MetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_MetadataRequest_descriptor,
        new java.lang.String[] { "Rows", });
    internal_static_google_spannerlib_v1_ResultSetStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_spannerlib_v1_ResultSetStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_ResultSetStatsRequest_descriptor,
        new java.lang.String[] { "Rows", });
    internal_static_google_spannerlib_v1_ConnectionStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_spannerlib_v1_ConnectionStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_ConnectionStreamRequest_descriptor,
        new java.lang.String[] { "ExecuteRequest", "ExecuteBatchRequest", "BeginTransactionRequest", "CommitRequest", "RollbackRequest", "WriteMutationsRequest", "Request", });
    internal_static_google_spannerlib_v1_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_spannerlib_v1_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_ExecuteResponse_descriptor,
        new java.lang.String[] { "Rows", "ResultSets", "Status", "HasMoreResults", });
    internal_static_google_spannerlib_v1_ConnectionStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_spannerlib_v1_ConnectionStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_spannerlib_v1_ConnectionStreamResponse_descriptor,
        new java.lang.String[] { "Status", "ExecuteResponse", "ExecuteBatchResponse", "BeginTransactionResponse", "CommitResponse", "RollbackResponse", "WriteMutationsResponse", "Response", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.spanner.v1.ResultSetProto.getDescriptor();
    com.google.spanner.v1.SpannerProto.getDescriptor();
    com.google.spanner.v1.TransactionProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
