# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rake", "~> 13.0"

group :development, :test do
  gem "rake-compiler", "~> 1.0"
  gem "rspec", "~> 3.0"
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
end
