# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in spannerlib-ruby.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem 'ffi'
gem 'google-protobuf', '~> 3.19'
gem 'grpc', '~> 1.60'
gem 'googleapis-common-protos', '~> 1.0'

gem 'google-cloud-spanner'