# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "rubocop/rake_task"
require "rbconfig"

RSpec::Core::RakeTask.new(:spec)

RuboCop::RakeTask.new

task :compile do
  go_source_dir = File.expand_path("../../shared", __dir__)
  target_dir = File.expand_path("lib/spannerlib/#{RbConfig::CONFIG['arch']}", __dir__)
  output_file = File.join(target_dir, "spannerlib.#{RbConfig::CONFIG['SOEXT']}")

  mkdir_p target_dir

  command = [
    "go", "build",
    "-buildmode=c-shared",
    "-o", output_file,
    go_source_dir
  ].join(" ")

  puts command
  sh command
end

task default: %i[compile spec rubocop]
