const { CreatePool, ClosePool } = require('../ffi/bindings.js');
const { toGoString, invokeAsync } = require('../ffi/utils.js');
const { spannerLib } = require('./spannerlib.js');
const { Connection } = require('./connection.js');

class Pool {
    /**
     * Initializes a Pool object by invoking the underlying CGO `CreatePool`.
     * Because FFI async spans the Go initialization process, we use `static async create`
     * to safely handle promises natively inside JS.
     */
    static async create(userAgent, connectionString) {
        const p = new Pool();
        const handled = await invokeAsync(
            CreatePool,
            p,         // Ref instance for memory registry
            spannerLib,// Our Memory manager
            toGoString(userAgent),
            toGoString(connectionString)
        );

        p.oid = handled.objectId;
        return p;
    }

    constructor() {
        /**
         * The Object ID (OID). 
         * This is a unique identifier generated by the underlying Go Spanner driver
         * to represent this specific Pool instance in its internal state map.
         * We pass this OID back to Go when we execute operations (like executeSql)
         * so Go knows which active Pool/Connection instance to use.
         * @type {Number|null}
         */
        this.oid = null;

    /**
     * The Memory Pinner ID.
     * Because Go Garbage Collection might move or delete objects currently
     * being used by Node.js over FFI, Go "pins" the memory in place and 
     * returns a Pinner ID. We must explicitly invoke Go's `Release(pinnerId)` 
     * when this object is closed to prevent CGO memory leaks.
     * @type {Number|null}
     */
        this.pinnerId = null;

        /**
         * State flag tracking whether this Pool has been explicitly closed.
         * @type {Boolean}
         */
        this.closed = false;
    }

    /**
     * Creates or borrows a new Connection within this Pool asynchronously.
     * @returns {Promise<Connection>}
     */
    async createConnection() {
        if (this.closed) throw new Error("Pool is already closed");
        return await Connection.create(this);
    }

    /**
     * Closes the underlying Go Spanner pool and explicitly drops memory pinned on Go's end.
     */
    async close() {
        if (!this.closed) {
            this.closed = true;
            try {
                // Background execution of close logic
                await invokeAsync(ClosePool, this, spannerLib, this.oid);
            } finally {
                // Explicitly unregister from the GC watcher, guaranteeing immediate cleanup
                spannerLib.unregister(this, this.pinnerId);
            }
        }
    }
}

module.exports = { Pool };
