// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: google/spannerlib/v1/spannerlib.proto

package spannerlibpb

import (
	spannerpb "cloud.google.com/go/spanner/apiv1/spannerpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreatePoolRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionString string                 `protobuf:"bytes,1,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePoolRequest) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type CreateConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *Pool                  `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectionRequest) Reset() {
	*x = CreateConnectionRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectionRequest) ProtoMessage() {}

func (x *CreateConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectionRequest.ProtoReflect.Descriptor instead.
func (*CreateConnectionRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConnectionRequest) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type ExecuteRequest struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Connection        *Connection                  `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	ExecuteSqlRequest *spannerpb.ExecuteSqlRequest `protobuf:"bytes,2,opt,name=execute_sql_request,json=executeSqlRequest,proto3" json:"execute_sql_request,omitempty"`
	FetchOptions      *FetchOptions                `protobuf:"bytes,3,opt,name=fetch_options,json=fetchOptions,proto3" json:"fetch_options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ExecuteRequest) GetExecuteSqlRequest() *spannerpb.ExecuteSqlRequest {
	if x != nil {
		return x.ExecuteSqlRequest
	}
	return nil
}

func (x *ExecuteRequest) GetFetchOptions() *FetchOptions {
	if x != nil {
		return x.FetchOptions
	}
	return nil
}

type ExecuteBatchRequest struct {
	state                  protoimpl.MessageState            `protogen:"open.v1"`
	Connection             *Connection                       `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	ExecuteBatchDmlRequest *spannerpb.ExecuteBatchDmlRequest `protobuf:"bytes,2,opt,name=execute_batch_dml_request,json=executeBatchDmlRequest,proto3" json:"execute_batch_dml_request,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecuteBatchRequest) Reset() {
	*x = ExecuteBatchRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchRequest) ProtoMessage() {}

func (x *ExecuteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteBatchRequest) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ExecuteBatchRequest) GetExecuteBatchDmlRequest() *spannerpb.ExecuteBatchDmlRequest {
	if x != nil {
		return x.ExecuteBatchDmlRequest
	}
	return nil
}

type BeginTransactionRequest struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	Connection         *Connection                   `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	TransactionOptions *spannerpb.TransactionOptions `protobuf:"bytes,2,opt,name=transaction_options,json=transactionOptions,proto3" json:"transaction_options,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{6}
}

func (x *BeginTransactionRequest) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *BeginTransactionRequest) GetTransactionOptions() *spannerpb.TransactionOptions {
	if x != nil {
		return x.TransactionOptions
	}
	return nil
}

type WriteMutationsRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Connection    *Connection                                `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Mutations     *spannerpb.BatchWriteRequest_MutationGroup `protobuf:"bytes,2,opt,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMutationsRequest) Reset() {
	*x = WriteMutationsRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMutationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMutationsRequest) ProtoMessage() {}

func (x *WriteMutationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMutationsRequest.ProtoReflect.Descriptor instead.
func (*WriteMutationsRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{7}
}

func (x *WriteMutationsRequest) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *WriteMutationsRequest) GetMutations() *spannerpb.BatchWriteRequest_MutationGroup {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{8}
}

func (x *Pool) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *Pool                  `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{9}
}

func (x *Connection) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *Connection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Rows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rows) Reset() {
	*x = Rows{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rows) ProtoMessage() {}

func (x *Rows) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rows.ProtoReflect.Descriptor instead.
func (*Rows) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{10}
}

func (x *Rows) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *Rows) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          *Rows                  `protobuf:"bytes,1,opt,name=rows,proto3" json:"rows,omitempty"`
	FetchOptions  *FetchOptions          `protobuf:"bytes,2,opt,name=fetch_options,json=fetchOptions,proto3" json:"fetch_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRequest) Reset() {
	*x = NextRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRequest) ProtoMessage() {}

func (x *NextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRequest.ProtoReflect.Descriptor instead.
func (*NextRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{11}
}

func (x *NextRequest) GetRows() *Rows {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *NextRequest) GetFetchOptions() *FetchOptions {
	if x != nil {
		return x.FetchOptions
	}
	return nil
}

type FetchOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumRows       int64                  `protobuf:"varint,1,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	Encoding      int64                  `protobuf:"varint,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOptions) Reset() {
	*x = FetchOptions{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOptions) ProtoMessage() {}

func (x *FetchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOptions.ProtoReflect.Descriptor instead.
func (*FetchOptions) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{12}
}

func (x *FetchOptions) GetNumRows() int64 {
	if x != nil {
		return x.NumRows
	}
	return 0
}

func (x *FetchOptions) GetEncoding() int64 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

type RowData struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	RequestId      string                       `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Rows           *Rows                        `protobuf:"bytes,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Metadata       *spannerpb.ResultSetMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data           []*structpb.ListValue        `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	Stats          *spannerpb.ResultSetStats    `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	HasMoreResults bool                         `protobuf:"varint,6,opt,name=has_more_results,json=hasMoreResults,proto3" json:"has_more_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RowData) Reset() {
	*x = RowData{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowData) ProtoMessage() {}

func (x *RowData) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowData.ProtoReflect.Descriptor instead.
func (*RowData) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{13}
}

func (x *RowData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RowData) GetRows() *Rows {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *RowData) GetMetadata() *spannerpb.ResultSetMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RowData) GetData() []*structpb.ListValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RowData) GetStats() *spannerpb.ResultSetStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *RowData) GetHasMoreResults() bool {
	if x != nil {
		return x.HasMoreResults
	}
	return false
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          *Rows                  `protobuf:"bytes,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{14}
}

func (x *MetadataRequest) GetRows() *Rows {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ResultSetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          *Rows                  `protobuf:"bytes,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultSetStatsRequest) Reset() {
	*x = ResultSetStatsRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultSetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSetStatsRequest) ProtoMessage() {}

func (x *ResultSetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSetStatsRequest.ProtoReflect.Descriptor instead.
func (*ResultSetStatsRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{15}
}

func (x *ResultSetStatsRequest) GetRows() *Rows {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ConnectionStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ConnectionStreamRequest_ExecuteRequest
	//	*ConnectionStreamRequest_ExecuteBatchRequest
	//	*ConnectionStreamRequest_BeginTransactionRequest
	//	*ConnectionStreamRequest_CommitRequest
	//	*ConnectionStreamRequest_RollbackRequest
	//	*ConnectionStreamRequest_WriteMutationsRequest
	Request       isConnectionStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStreamRequest) Reset() {
	*x = ConnectionStreamRequest{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStreamRequest) ProtoMessage() {}

func (x *ConnectionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStreamRequest.ProtoReflect.Descriptor instead.
func (*ConnectionStreamRequest) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{16}
}

func (x *ConnectionStreamRequest) GetRequest() isConnectionStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ConnectionStreamRequest) GetExecuteRequest() *ExecuteRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectionStreamRequest_ExecuteRequest); ok {
			return x.ExecuteRequest
		}
	}
	return nil
}

func (x *ConnectionStreamRequest) GetExecuteBatchRequest() *ExecuteBatchRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectionStreamRequest_ExecuteBatchRequest); ok {
			return x.ExecuteBatchRequest
		}
	}
	return nil
}

func (x *ConnectionStreamRequest) GetBeginTransactionRequest() *BeginTransactionRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectionStreamRequest_BeginTransactionRequest); ok {
			return x.BeginTransactionRequest
		}
	}
	return nil
}

func (x *ConnectionStreamRequest) GetCommitRequest() *Connection {
	if x != nil {
		if x, ok := x.Request.(*ConnectionStreamRequest_CommitRequest); ok {
			return x.CommitRequest
		}
	}
	return nil
}

func (x *ConnectionStreamRequest) GetRollbackRequest() *Connection {
	if x != nil {
		if x, ok := x.Request.(*ConnectionStreamRequest_RollbackRequest); ok {
			return x.RollbackRequest
		}
	}
	return nil
}

func (x *ConnectionStreamRequest) GetWriteMutationsRequest() *WriteMutationsRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectionStreamRequest_WriteMutationsRequest); ok {
			return x.WriteMutationsRequest
		}
	}
	return nil
}

type isConnectionStreamRequest_Request interface {
	isConnectionStreamRequest_Request()
}

type ConnectionStreamRequest_ExecuteRequest struct {
	ExecuteRequest *ExecuteRequest `protobuf:"bytes,1,opt,name=execute_request,json=executeRequest,proto3,oneof"`
}

type ConnectionStreamRequest_ExecuteBatchRequest struct {
	ExecuteBatchRequest *ExecuteBatchRequest `protobuf:"bytes,2,opt,name=execute_batch_request,json=executeBatchRequest,proto3,oneof"`
}

type ConnectionStreamRequest_BeginTransactionRequest struct {
	BeginTransactionRequest *BeginTransactionRequest `protobuf:"bytes,3,opt,name=begin_transaction_request,json=beginTransactionRequest,proto3,oneof"`
}

type ConnectionStreamRequest_CommitRequest struct {
	CommitRequest *Connection `protobuf:"bytes,4,opt,name=commit_request,json=commitRequest,proto3,oneof"`
}

type ConnectionStreamRequest_RollbackRequest struct {
	RollbackRequest *Connection `protobuf:"bytes,5,opt,name=rollback_request,json=rollbackRequest,proto3,oneof"`
}

type ConnectionStreamRequest_WriteMutationsRequest struct {
	WriteMutationsRequest *WriteMutationsRequest `protobuf:"bytes,6,opt,name=write_mutations_request,json=writeMutationsRequest,proto3,oneof"`
}

func (*ConnectionStreamRequest_ExecuteRequest) isConnectionStreamRequest_Request() {}

func (*ConnectionStreamRequest_ExecuteBatchRequest) isConnectionStreamRequest_Request() {}

func (*ConnectionStreamRequest_BeginTransactionRequest) isConnectionStreamRequest_Request() {}

func (*ConnectionStreamRequest_CommitRequest) isConnectionStreamRequest_Request() {}

func (*ConnectionStreamRequest_RollbackRequest) isConnectionStreamRequest_Request() {}

func (*ConnectionStreamRequest_WriteMutationsRequest) isConnectionStreamRequest_Request() {}

type ExecuteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rows           *Rows                  `protobuf:"bytes,1,opt,name=rows,proto3" json:"rows,omitempty"`
	ResultSets     []*spannerpb.ResultSet `protobuf:"bytes,2,rep,name=result_sets,json=resultSets,proto3" json:"result_sets,omitempty"`
	Status         *status.Status         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	HasMoreResults bool                   `protobuf:"varint,4,opt,name=has_more_results,json=hasMoreResults,proto3" json:"has_more_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteResponse) GetRows() *Rows {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExecuteResponse) GetResultSets() []*spannerpb.ResultSet {
	if x != nil {
		return x.ResultSets
	}
	return nil
}

func (x *ExecuteResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExecuteResponse) GetHasMoreResults() bool {
	if x != nil {
		return x.HasMoreResults
	}
	return false
}

type ConnectionStreamResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*ConnectionStreamResponse_ExecuteResponse
	//	*ConnectionStreamResponse_ExecuteBatchResponse
	//	*ConnectionStreamResponse_BeginTransactionResponse
	//	*ConnectionStreamResponse_CommitResponse
	//	*ConnectionStreamResponse_RollbackResponse
	//	*ConnectionStreamResponse_WriteMutationsResponse
	Response      isConnectionStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStreamResponse) Reset() {
	*x = ConnectionStreamResponse{}
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStreamResponse) ProtoMessage() {}

func (x *ConnectionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_spannerlib_v1_spannerlib_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStreamResponse.ProtoReflect.Descriptor instead.
func (*ConnectionStreamResponse) Descriptor() ([]byte, []int) {
	return file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectionStreamResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConnectionStreamResponse) GetResponse() isConnectionStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ConnectionStreamResponse) GetExecuteResponse() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectionStreamResponse_ExecuteResponse); ok {
			return x.ExecuteResponse
		}
	}
	return nil
}

func (x *ConnectionStreamResponse) GetExecuteBatchResponse() *spannerpb.ExecuteBatchDmlResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectionStreamResponse_ExecuteBatchResponse); ok {
			return x.ExecuteBatchResponse
		}
	}
	return nil
}

func (x *ConnectionStreamResponse) GetBeginTransactionResponse() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Response.(*ConnectionStreamResponse_BeginTransactionResponse); ok {
			return x.BeginTransactionResponse
		}
	}
	return nil
}

func (x *ConnectionStreamResponse) GetCommitResponse() *spannerpb.CommitResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectionStreamResponse_CommitResponse); ok {
			return x.CommitResponse
		}
	}
	return nil
}

func (x *ConnectionStreamResponse) GetRollbackResponse() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Response.(*ConnectionStreamResponse_RollbackResponse); ok {
			return x.RollbackResponse
		}
	}
	return nil
}

func (x *ConnectionStreamResponse) GetWriteMutationsResponse() *spannerpb.CommitResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectionStreamResponse_WriteMutationsResponse); ok {
			return x.WriteMutationsResponse
		}
	}
	return nil
}

type isConnectionStreamResponse_Response interface {
	isConnectionStreamResponse_Response()
}

type ConnectionStreamResponse_ExecuteResponse struct {
	ExecuteResponse *ExecuteResponse `protobuf:"bytes,2,opt,name=execute_response,json=executeResponse,proto3,oneof"`
}

type ConnectionStreamResponse_ExecuteBatchResponse struct {
	ExecuteBatchResponse *spannerpb.ExecuteBatchDmlResponse `protobuf:"bytes,3,opt,name=execute_batch_response,json=executeBatchResponse,proto3,oneof"`
}

type ConnectionStreamResponse_BeginTransactionResponse struct {
	BeginTransactionResponse *emptypb.Empty `protobuf:"bytes,4,opt,name=begin_transaction_response,json=beginTransactionResponse,proto3,oneof"`
}

type ConnectionStreamResponse_CommitResponse struct {
	CommitResponse *spannerpb.CommitResponse `protobuf:"bytes,5,opt,name=commit_response,json=commitResponse,proto3,oneof"`
}

type ConnectionStreamResponse_RollbackResponse struct {
	RollbackResponse *emptypb.Empty `protobuf:"bytes,6,opt,name=rollback_response,json=rollbackResponse,proto3,oneof"`
}

type ConnectionStreamResponse_WriteMutationsResponse struct {
	WriteMutationsResponse *spannerpb.CommitResponse `protobuf:"bytes,7,opt,name=write_mutations_response,json=writeMutationsResponse,proto3,oneof"`
}

func (*ConnectionStreamResponse_ExecuteResponse) isConnectionStreamResponse_Response() {}

func (*ConnectionStreamResponse_ExecuteBatchResponse) isConnectionStreamResponse_Response() {}

func (*ConnectionStreamResponse_BeginTransactionResponse) isConnectionStreamResponse_Response() {}

func (*ConnectionStreamResponse_CommitResponse) isConnectionStreamResponse_Response() {}

func (*ConnectionStreamResponse_RollbackResponse) isConnectionStreamResponse_Response() {}

func (*ConnectionStreamResponse_WriteMutationsResponse) isConnectionStreamResponse_Response() {}

var File_google_spannerlib_v1_spannerlib_proto protoreflect.FileDescriptor

const file_google_spannerlib_v1_spannerlib_proto_rawDesc = "" +
	"\n" +
	"%google/spannerlib/v1/spannerlib.proto\x12\x14google.spannerlib.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17google/rpc/status.proto\x1a\"google/spanner/v1/result_set.proto\x1a\x1fgoogle/spanner/v1/spanner.proto\x1a#google/spanner/v1/transaction.proto\"\r\n" +
	"\vInfoRequest\"(\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"E\n" +
	"\x11CreatePoolRequest\x120\n" +
	"\x11connection_string\x18\x01 \x01(\tB\x03\xe0A\x02R\x10connectionString\"N\n" +
	"\x17CreateConnectionRequest\x123\n" +
	"\x04pool\x18\x01 \x01(\v2\x1a.google.spannerlib.v1.PoolB\x03\xe0A\x02R\x04pool\"\xfb\x01\n" +
	"\x0eExecuteRequest\x12E\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .google.spannerlib.v1.ConnectionB\x03\xe0A\x02R\n" +
	"connection\x12Y\n" +
	"\x13execute_sql_request\x18\x02 \x01(\v2$.google.spanner.v1.ExecuteSqlRequestB\x03\xe0A\x02R\x11executeSqlRequest\x12G\n" +
	"\rfetch_options\x18\x03 \x01(\v2\".google.spannerlib.v1.FetchOptionsR\ffetchOptions\"\xc7\x01\n" +
	"\x13ExecuteBatchRequest\x12E\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .google.spannerlib.v1.ConnectionB\x03\xe0A\x02R\n" +
	"connection\x12i\n" +
	"\x19execute_batch_dml_request\x18\x02 \x01(\v2).google.spanner.v1.ExecuteBatchDmlRequestB\x03\xe0A\x02R\x16executeBatchDmlRequest\"\xbd\x01\n" +
	"\x17BeginTransactionRequest\x12E\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .google.spannerlib.v1.ConnectionB\x03\xe0A\x02R\n" +
	"connection\x12[\n" +
	"\x13transaction_options\x18\x02 \x01(\v2%.google.spanner.v1.TransactionOptionsB\x03\xe0A\x02R\x12transactionOptions\"\xb5\x01\n" +
	"\x15WriteMutationsRequest\x12E\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .google.spannerlib.v1.ConnectionB\x03\xe0A\x02R\n" +
	"connection\x12U\n" +
	"\tmutations\x18\x02 \x01(\v22.google.spanner.v1.BatchWriteRequest.MutationGroupB\x03\xe0A\x02R\tmutations\"\x1b\n" +
	"\x04Pool\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"V\n" +
	"\n" +
	"Connection\x123\n" +
	"\x04pool\x18\x01 \x01(\v2\x1a.google.spannerlib.v1.PoolB\x03\xe0A\x02R\x04pool\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\"b\n" +
	"\x04Rows\x12E\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .google.spannerlib.v1.ConnectionB\x03\xe0A\x02R\n" +
	"connection\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\"\x90\x01\n" +
	"\vNextRequest\x123\n" +
	"\x04rows\x18\x01 \x01(\v2\x1a.google.spannerlib.v1.RowsB\x03\xe0A\x02R\x04rows\x12L\n" +
	"\rfetch_options\x18\x02 \x01(\v2\".google.spannerlib.v1.FetchOptionsB\x03\xe0A\x02R\ffetchOptions\"O\n" +
	"\fFetchOptions\x12\x1e\n" +
	"\bnum_rows\x18\x01 \x01(\x03B\x03\xe0A\x02R\anumRows\x12\x1f\n" +
	"\bencoding\x18\x02 \x01(\x03B\x03\xe0A\x02R\bencoding\"\xb7\x02\n" +
	"\aRowData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\x04rows\x18\x02 \x01(\v2\x1a.google.spannerlib.v1.RowsB\x03\xe0A\x02R\x04rows\x12@\n" +
	"\bmetadata\x18\x03 \x01(\v2$.google.spanner.v1.ResultSetMetadataR\bmetadata\x123\n" +
	"\x04data\x18\x04 \x03(\v2\x1a.google.protobuf.ListValueB\x03\xe0A\x02R\x04data\x127\n" +
	"\x05stats\x18\x05 \x01(\v2!.google.spanner.v1.ResultSetStatsR\x05stats\x12(\n" +
	"\x10has_more_results\x18\x06 \x01(\bR\x0ehasMoreResults\"F\n" +
	"\x0fMetadataRequest\x123\n" +
	"\x04rows\x18\x01 \x01(\v2\x1a.google.spannerlib.v1.RowsB\x03\xe0A\x02R\x04rows\"L\n" +
	"\x15ResultSetStatsRequest\x123\n" +
	"\x04rows\x18\x01 \x01(\v2\x1a.google.spannerlib.v1.RowsB\x03\xe0A\x02R\x04rows\"\xc4\x04\n" +
	"\x17ConnectionStreamRequest\x12O\n" +
	"\x0fexecute_request\x18\x01 \x01(\v2$.google.spannerlib.v1.ExecuteRequestH\x00R\x0eexecuteRequest\x12_\n" +
	"\x15execute_batch_request\x18\x02 \x01(\v2).google.spannerlib.v1.ExecuteBatchRequestH\x00R\x13executeBatchRequest\x12k\n" +
	"\x19begin_transaction_request\x18\x03 \x01(\v2-.google.spannerlib.v1.BeginTransactionRequestH\x00R\x17beginTransactionRequest\x12I\n" +
	"\x0ecommit_request\x18\x04 \x01(\v2 .google.spannerlib.v1.ConnectionH\x00R\rcommitRequest\x12M\n" +
	"\x10rollback_request\x18\x05 \x01(\v2 .google.spannerlib.v1.ConnectionH\x00R\x0frollbackRequest\x12e\n" +
	"\x17write_mutations_request\x18\x06 \x01(\v2+.google.spannerlib.v1.WriteMutationsRequestH\x00R\x15writeMutationsRequestB\t\n" +
	"\arequest\"\xdb\x01\n" +
	"\x0fExecuteResponse\x123\n" +
	"\x04rows\x18\x01 \x01(\v2\x1a.google.spannerlib.v1.RowsB\x03\xe0A\x02R\x04rows\x12=\n" +
	"\vresult_sets\x18\x02 \x03(\v2\x1c.google.spanner.v1.ResultSetR\n" +
	"resultSets\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\x12(\n" +
	"\x10has_more_results\x18\x04 \x01(\bR\x0ehasMoreResults\"\xd6\x04\n" +
	"\x18ConnectionStreamResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12R\n" +
	"\x10execute_response\x18\x02 \x01(\v2%.google.spannerlib.v1.ExecuteResponseH\x00R\x0fexecuteResponse\x12b\n" +
	"\x16execute_batch_response\x18\x03 \x01(\v2*.google.spanner.v1.ExecuteBatchDmlResponseH\x00R\x14executeBatchResponse\x12V\n" +
	"\x1abegin_transaction_response\x18\x04 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x18beginTransactionResponse\x12L\n" +
	"\x0fcommit_response\x18\x05 \x01(\v2!.google.spanner.v1.CommitResponseH\x00R\x0ecommitResponse\x12E\n" +
	"\x11rollback_response\x18\x06 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x10rollbackResponse\x12]\n" +
	"\x18write_mutations_response\x18\a \x01(\v2!.google.spanner.v1.CommitResponseH\x00R\x16writeMutationsResponseB\n" +
	"\n" +
	"\bresponse2\xeb\f\n" +
	"\n" +
	"SpannerLib\x12O\n" +
	"\x04Info\x12!.google.spannerlib.v1.InfoRequest\x1a\".google.spannerlib.v1.InfoResponse\"\x00\x12S\n" +
	"\n" +
	"CreatePool\x12'.google.spannerlib.v1.CreatePoolRequest\x1a\x1a.google.spannerlib.v1.Pool\"\x00\x12A\n" +
	"\tClosePool\x12\x1a.google.spannerlib.v1.Pool\x1a\x16.google.protobuf.Empty\"\x00\x12e\n" +
	"\x10CreateConnection\x12-.google.spannerlib.v1.CreateConnectionRequest\x1a .google.spannerlib.v1.Connection\"\x00\x12M\n" +
	"\x0fCloseConnection\x12 .google.spannerlib.v1.Connection\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\aExecute\x12$.google.spannerlib.v1.ExecuteRequest\x1a\x1a.google.spannerlib.v1.Rows\"\x00\x12[\n" +
	"\x10ExecuteStreaming\x12$.google.spannerlib.v1.ExecuteRequest\x1a\x1d.google.spannerlib.v1.RowData\"\x000\x01\x12g\n" +
	"\fExecuteBatch\x12).google.spannerlib.v1.ExecuteBatchRequest\x1a*.google.spanner.v1.ExecuteBatchDmlResponse\"\x00\x12N\n" +
	"\bMetadata\x12\x1a.google.spannerlib.v1.Rows\x1a$.google.spanner.v1.ResultSetMetadata\"\x00\x12G\n" +
	"\x04Next\x12!.google.spannerlib.v1.NextRequest\x1a\x1a.google.protobuf.ListValue\"\x00\x12Q\n" +
	"\x0eResultSetStats\x12\x1a.google.spannerlib.v1.Rows\x1a!.google.spanner.v1.ResultSetStats\"\x00\x12S\n" +
	"\rNextResultSet\x12\x1a.google.spannerlib.v1.Rows\x1a$.google.spanner.v1.ResultSetMetadata\"\x00\x12A\n" +
	"\tCloseRows\x12\x1a.google.spannerlib.v1.Rows\x1a\x16.google.protobuf.Empty\"\x00\x12[\n" +
	"\x10BeginTransaction\x12-.google.spannerlib.v1.BeginTransactionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x06Commit\x12 .google.spannerlib.v1.Connection\x1a!.google.spanner.v1.CommitResponse\"\x00\x12F\n" +
	"\bRollback\x12 .google.spannerlib.v1.Connection\x1a\x16.google.protobuf.Empty\"\x00\x12b\n" +
	"\x0eWriteMutations\x12+.google.spannerlib.v1.WriteMutationsRequest\x1a!.google.spanner.v1.CommitResponse\"\x00\x12w\n" +
	"\x10ConnectionStream\x12-.google.spannerlib.v1.ConnectionStreamRequest\x1a..google.spannerlib.v1.ConnectionStreamResponse\"\x00(\x010\x01\x12R\n" +
	"\x11ContinueStreaming\x12\x1a.google.spannerlib.v1.Rows\x1a\x1d.google.spannerlib.v1.RowData\"\x000\x01B\xcd\x01\n" +
	"\x1ecom.google.cloud.spannerlib.v1B\x0fSpannerLibProtoP\x01Z>cloud.google.com/go/spannerlib/apiv1/spannerlibpb;spannerlibpb\xaa\x02\x1aGoogle.Cloud.SpannerLib.V1\xca\x02\x1aGoogle\\Cloud\\SpannerLib\\V1\xea\x02\x1dGoogle::Cloud::SpannerLib::V1b\x06proto3"

var (
	file_google_spannerlib_v1_spannerlib_proto_rawDescOnce sync.Once
	file_google_spannerlib_v1_spannerlib_proto_rawDescData []byte
)

func file_google_spannerlib_v1_spannerlib_proto_rawDescGZIP() []byte {
	file_google_spannerlib_v1_spannerlib_proto_rawDescOnce.Do(func() {
		file_google_spannerlib_v1_spannerlib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_spannerlib_v1_spannerlib_proto_rawDesc), len(file_google_spannerlib_v1_spannerlib_proto_rawDesc)))
	})
	return file_google_spannerlib_v1_spannerlib_proto_rawDescData
}

var file_google_spannerlib_v1_spannerlib_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_google_spannerlib_v1_spannerlib_proto_goTypes = []any{
	(*InfoRequest)(nil),                               // 0: google.spannerlib.v1.InfoRequest
	(*InfoResponse)(nil),                              // 1: google.spannerlib.v1.InfoResponse
	(*CreatePoolRequest)(nil),                         // 2: google.spannerlib.v1.CreatePoolRequest
	(*CreateConnectionRequest)(nil),                   // 3: google.spannerlib.v1.CreateConnectionRequest
	(*ExecuteRequest)(nil),                            // 4: google.spannerlib.v1.ExecuteRequest
	(*ExecuteBatchRequest)(nil),                       // 5: google.spannerlib.v1.ExecuteBatchRequest
	(*BeginTransactionRequest)(nil),                   // 6: google.spannerlib.v1.BeginTransactionRequest
	(*WriteMutationsRequest)(nil),                     // 7: google.spannerlib.v1.WriteMutationsRequest
	(*Pool)(nil),                                      // 8: google.spannerlib.v1.Pool
	(*Connection)(nil),                                // 9: google.spannerlib.v1.Connection
	(*Rows)(nil),                                      // 10: google.spannerlib.v1.Rows
	(*NextRequest)(nil),                               // 11: google.spannerlib.v1.NextRequest
	(*FetchOptions)(nil),                              // 12: google.spannerlib.v1.FetchOptions
	(*RowData)(nil),                                   // 13: google.spannerlib.v1.RowData
	(*MetadataRequest)(nil),                           // 14: google.spannerlib.v1.MetadataRequest
	(*ResultSetStatsRequest)(nil),                     // 15: google.spannerlib.v1.ResultSetStatsRequest
	(*ConnectionStreamRequest)(nil),                   // 16: google.spannerlib.v1.ConnectionStreamRequest
	(*ExecuteResponse)(nil),                           // 17: google.spannerlib.v1.ExecuteResponse
	(*ConnectionStreamResponse)(nil),                  // 18: google.spannerlib.v1.ConnectionStreamResponse
	(*spannerpb.ExecuteSqlRequest)(nil),               // 19: google.spanner.v1.ExecuteSqlRequest
	(*spannerpb.ExecuteBatchDmlRequest)(nil),          // 20: google.spanner.v1.ExecuteBatchDmlRequest
	(*spannerpb.TransactionOptions)(nil),              // 21: google.spanner.v1.TransactionOptions
	(*spannerpb.BatchWriteRequest_MutationGroup)(nil), // 22: google.spanner.v1.BatchWriteRequest.MutationGroup
	(*spannerpb.ResultSetMetadata)(nil),               // 23: google.spanner.v1.ResultSetMetadata
	(*structpb.ListValue)(nil),                        // 24: google.protobuf.ListValue
	(*spannerpb.ResultSetStats)(nil),                  // 25: google.spanner.v1.ResultSetStats
	(*spannerpb.ResultSet)(nil),                       // 26: google.spanner.v1.ResultSet
	(*status.Status)(nil),                             // 27: google.rpc.Status
	(*spannerpb.ExecuteBatchDmlResponse)(nil),         // 28: google.spanner.v1.ExecuteBatchDmlResponse
	(*emptypb.Empty)(nil),                             // 29: google.protobuf.Empty
	(*spannerpb.CommitResponse)(nil),                  // 30: google.spanner.v1.CommitResponse
}
var file_google_spannerlib_v1_spannerlib_proto_depIdxs = []int32{
	8,  // 0: google.spannerlib.v1.CreateConnectionRequest.pool:type_name -> google.spannerlib.v1.Pool
	9,  // 1: google.spannerlib.v1.ExecuteRequest.connection:type_name -> google.spannerlib.v1.Connection
	19, // 2: google.spannerlib.v1.ExecuteRequest.execute_sql_request:type_name -> google.spanner.v1.ExecuteSqlRequest
	12, // 3: google.spannerlib.v1.ExecuteRequest.fetch_options:type_name -> google.spannerlib.v1.FetchOptions
	9,  // 4: google.spannerlib.v1.ExecuteBatchRequest.connection:type_name -> google.spannerlib.v1.Connection
	20, // 5: google.spannerlib.v1.ExecuteBatchRequest.execute_batch_dml_request:type_name -> google.spanner.v1.ExecuteBatchDmlRequest
	9,  // 6: google.spannerlib.v1.BeginTransactionRequest.connection:type_name -> google.spannerlib.v1.Connection
	21, // 7: google.spannerlib.v1.BeginTransactionRequest.transaction_options:type_name -> google.spanner.v1.TransactionOptions
	9,  // 8: google.spannerlib.v1.WriteMutationsRequest.connection:type_name -> google.spannerlib.v1.Connection
	22, // 9: google.spannerlib.v1.WriteMutationsRequest.mutations:type_name -> google.spanner.v1.BatchWriteRequest.MutationGroup
	8,  // 10: google.spannerlib.v1.Connection.pool:type_name -> google.spannerlib.v1.Pool
	9,  // 11: google.spannerlib.v1.Rows.connection:type_name -> google.spannerlib.v1.Connection
	10, // 12: google.spannerlib.v1.NextRequest.rows:type_name -> google.spannerlib.v1.Rows
	12, // 13: google.spannerlib.v1.NextRequest.fetch_options:type_name -> google.spannerlib.v1.FetchOptions
	10, // 14: google.spannerlib.v1.RowData.rows:type_name -> google.spannerlib.v1.Rows
	23, // 15: google.spannerlib.v1.RowData.metadata:type_name -> google.spanner.v1.ResultSetMetadata
	24, // 16: google.spannerlib.v1.RowData.data:type_name -> google.protobuf.ListValue
	25, // 17: google.spannerlib.v1.RowData.stats:type_name -> google.spanner.v1.ResultSetStats
	10, // 18: google.spannerlib.v1.MetadataRequest.rows:type_name -> google.spannerlib.v1.Rows
	10, // 19: google.spannerlib.v1.ResultSetStatsRequest.rows:type_name -> google.spannerlib.v1.Rows
	4,  // 20: google.spannerlib.v1.ConnectionStreamRequest.execute_request:type_name -> google.spannerlib.v1.ExecuteRequest
	5,  // 21: google.spannerlib.v1.ConnectionStreamRequest.execute_batch_request:type_name -> google.spannerlib.v1.ExecuteBatchRequest
	6,  // 22: google.spannerlib.v1.ConnectionStreamRequest.begin_transaction_request:type_name -> google.spannerlib.v1.BeginTransactionRequest
	9,  // 23: google.spannerlib.v1.ConnectionStreamRequest.commit_request:type_name -> google.spannerlib.v1.Connection
	9,  // 24: google.spannerlib.v1.ConnectionStreamRequest.rollback_request:type_name -> google.spannerlib.v1.Connection
	7,  // 25: google.spannerlib.v1.ConnectionStreamRequest.write_mutations_request:type_name -> google.spannerlib.v1.WriteMutationsRequest
	10, // 26: google.spannerlib.v1.ExecuteResponse.rows:type_name -> google.spannerlib.v1.Rows
	26, // 27: google.spannerlib.v1.ExecuteResponse.result_sets:type_name -> google.spanner.v1.ResultSet
	27, // 28: google.spannerlib.v1.ExecuteResponse.status:type_name -> google.rpc.Status
	27, // 29: google.spannerlib.v1.ConnectionStreamResponse.status:type_name -> google.rpc.Status
	17, // 30: google.spannerlib.v1.ConnectionStreamResponse.execute_response:type_name -> google.spannerlib.v1.ExecuteResponse
	28, // 31: google.spannerlib.v1.ConnectionStreamResponse.execute_batch_response:type_name -> google.spanner.v1.ExecuteBatchDmlResponse
	29, // 32: google.spannerlib.v1.ConnectionStreamResponse.begin_transaction_response:type_name -> google.protobuf.Empty
	30, // 33: google.spannerlib.v1.ConnectionStreamResponse.commit_response:type_name -> google.spanner.v1.CommitResponse
	29, // 34: google.spannerlib.v1.ConnectionStreamResponse.rollback_response:type_name -> google.protobuf.Empty
	30, // 35: google.spannerlib.v1.ConnectionStreamResponse.write_mutations_response:type_name -> google.spanner.v1.CommitResponse
	0,  // 36: google.spannerlib.v1.SpannerLib.Info:input_type -> google.spannerlib.v1.InfoRequest
	2,  // 37: google.spannerlib.v1.SpannerLib.CreatePool:input_type -> google.spannerlib.v1.CreatePoolRequest
	8,  // 38: google.spannerlib.v1.SpannerLib.ClosePool:input_type -> google.spannerlib.v1.Pool
	3,  // 39: google.spannerlib.v1.SpannerLib.CreateConnection:input_type -> google.spannerlib.v1.CreateConnectionRequest
	9,  // 40: google.spannerlib.v1.SpannerLib.CloseConnection:input_type -> google.spannerlib.v1.Connection
	4,  // 41: google.spannerlib.v1.SpannerLib.Execute:input_type -> google.spannerlib.v1.ExecuteRequest
	4,  // 42: google.spannerlib.v1.SpannerLib.ExecuteStreaming:input_type -> google.spannerlib.v1.ExecuteRequest
	5,  // 43: google.spannerlib.v1.SpannerLib.ExecuteBatch:input_type -> google.spannerlib.v1.ExecuteBatchRequest
	10, // 44: google.spannerlib.v1.SpannerLib.Metadata:input_type -> google.spannerlib.v1.Rows
	11, // 45: google.spannerlib.v1.SpannerLib.Next:input_type -> google.spannerlib.v1.NextRequest
	10, // 46: google.spannerlib.v1.SpannerLib.ResultSetStats:input_type -> google.spannerlib.v1.Rows
	10, // 47: google.spannerlib.v1.SpannerLib.NextResultSet:input_type -> google.spannerlib.v1.Rows
	10, // 48: google.spannerlib.v1.SpannerLib.CloseRows:input_type -> google.spannerlib.v1.Rows
	6,  // 49: google.spannerlib.v1.SpannerLib.BeginTransaction:input_type -> google.spannerlib.v1.BeginTransactionRequest
	9,  // 50: google.spannerlib.v1.SpannerLib.Commit:input_type -> google.spannerlib.v1.Connection
	9,  // 51: google.spannerlib.v1.SpannerLib.Rollback:input_type -> google.spannerlib.v1.Connection
	7,  // 52: google.spannerlib.v1.SpannerLib.WriteMutations:input_type -> google.spannerlib.v1.WriteMutationsRequest
	16, // 53: google.spannerlib.v1.SpannerLib.ConnectionStream:input_type -> google.spannerlib.v1.ConnectionStreamRequest
	10, // 54: google.spannerlib.v1.SpannerLib.ContinueStreaming:input_type -> google.spannerlib.v1.Rows
	1,  // 55: google.spannerlib.v1.SpannerLib.Info:output_type -> google.spannerlib.v1.InfoResponse
	8,  // 56: google.spannerlib.v1.SpannerLib.CreatePool:output_type -> google.spannerlib.v1.Pool
	29, // 57: google.spannerlib.v1.SpannerLib.ClosePool:output_type -> google.protobuf.Empty
	9,  // 58: google.spannerlib.v1.SpannerLib.CreateConnection:output_type -> google.spannerlib.v1.Connection
	29, // 59: google.spannerlib.v1.SpannerLib.CloseConnection:output_type -> google.protobuf.Empty
	10, // 60: google.spannerlib.v1.SpannerLib.Execute:output_type -> google.spannerlib.v1.Rows
	13, // 61: google.spannerlib.v1.SpannerLib.ExecuteStreaming:output_type -> google.spannerlib.v1.RowData
	28, // 62: google.spannerlib.v1.SpannerLib.ExecuteBatch:output_type -> google.spanner.v1.ExecuteBatchDmlResponse
	23, // 63: google.spannerlib.v1.SpannerLib.Metadata:output_type -> google.spanner.v1.ResultSetMetadata
	24, // 64: google.spannerlib.v1.SpannerLib.Next:output_type -> google.protobuf.ListValue
	25, // 65: google.spannerlib.v1.SpannerLib.ResultSetStats:output_type -> google.spanner.v1.ResultSetStats
	23, // 66: google.spannerlib.v1.SpannerLib.NextResultSet:output_type -> google.spanner.v1.ResultSetMetadata
	29, // 67: google.spannerlib.v1.SpannerLib.CloseRows:output_type -> google.protobuf.Empty
	29, // 68: google.spannerlib.v1.SpannerLib.BeginTransaction:output_type -> google.protobuf.Empty
	30, // 69: google.spannerlib.v1.SpannerLib.Commit:output_type -> google.spanner.v1.CommitResponse
	29, // 70: google.spannerlib.v1.SpannerLib.Rollback:output_type -> google.protobuf.Empty
	30, // 71: google.spannerlib.v1.SpannerLib.WriteMutations:output_type -> google.spanner.v1.CommitResponse
	18, // 72: google.spannerlib.v1.SpannerLib.ConnectionStream:output_type -> google.spannerlib.v1.ConnectionStreamResponse
	13, // 73: google.spannerlib.v1.SpannerLib.ContinueStreaming:output_type -> google.spannerlib.v1.RowData
	55, // [55:74] is the sub-list for method output_type
	36, // [36:55] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_google_spannerlib_v1_spannerlib_proto_init() }
func file_google_spannerlib_v1_spannerlib_proto_init() {
	if File_google_spannerlib_v1_spannerlib_proto != nil {
		return
	}
	file_google_spannerlib_v1_spannerlib_proto_msgTypes[16].OneofWrappers = []any{
		(*ConnectionStreamRequest_ExecuteRequest)(nil),
		(*ConnectionStreamRequest_ExecuteBatchRequest)(nil),
		(*ConnectionStreamRequest_BeginTransactionRequest)(nil),
		(*ConnectionStreamRequest_CommitRequest)(nil),
		(*ConnectionStreamRequest_RollbackRequest)(nil),
		(*ConnectionStreamRequest_WriteMutationsRequest)(nil),
	}
	file_google_spannerlib_v1_spannerlib_proto_msgTypes[18].OneofWrappers = []any{
		(*ConnectionStreamResponse_ExecuteResponse)(nil),
		(*ConnectionStreamResponse_ExecuteBatchResponse)(nil),
		(*ConnectionStreamResponse_BeginTransactionResponse)(nil),
		(*ConnectionStreamResponse_CommitResponse)(nil),
		(*ConnectionStreamResponse_RollbackResponse)(nil),
		(*ConnectionStreamResponse_WriteMutationsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_spannerlib_v1_spannerlib_proto_rawDesc), len(file_google_spannerlib_v1_spannerlib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_spannerlib_v1_spannerlib_proto_goTypes,
		DependencyIndexes: file_google_spannerlib_v1_spannerlib_proto_depIdxs,
		MessageInfos:      file_google_spannerlib_v1_spannerlib_proto_msgTypes,
	}.Build()
	File_google_spannerlib_v1_spannerlib_proto = out.File
	file_google_spannerlib_v1_spannerlib_proto_goTypes = nil
	file_google_spannerlib_v1_spannerlib_proto_depIdxs = nil
}
