on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
  pull-requests: write
name: Build and Release Google.Cloud.SpannerLib
jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore
        working-directory: spannerlib/dotnet-spannerlib
      - name: Build
        run: dotnet build --no-restore
        working-directory: spannerlib/dotnet-spannerlib
      - name: Unit Tests
        working-directory: spannerlib/dotnet-spannerlib/Google.Cloud.SpannerLib.Tests
        run: dotnet test --no-build --verbosity normal
      - name: Pack SpannerLib
        run: dotnet pack
        working-directory: spannerlib/dotnet-spannerlib/Google.Cloud.SpannerLib
      - name: Publish SpannerLib to nuget
        run: dotnet nuget push bin/Release/Experimental.SpannerLib.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: spannerlib/dotnet-spannerlib/Google.Cloud.SpannerLib
