on:
  pull_request:
name: Run Samples

permissions:
  contents: read

jobs:
  samples:
    strategy:
      matrix:
        go-version: [1.25.x, 1.26.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run samples
        working-directory: ./examples
        run: go test -short
