on:
  pull_request:
name: Run Snippets
jobs:
  samples:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run snippets
        working-directory: ./snippets
        run: go test -short
