on:
  pull_request:
    branches: [ main ]
name: Run Snippets
jobs:
  samples:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run snippets
        working-directory: ./snippets
        run: go test -short
